# Generated by Django 3.2.23 on 2023-12-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0007_alter_emailtemplate_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="name",
            field=models.CharField(
                choices=[
                    ("project_received", "Projet bien reçu"),
                    ("project_accepted", "Projet accepté par l'équipe de modération"),
                    ("project_reminders_digest", "Résumé des rappels"),
                    (
                        "digest_for_non_switchtender",
                        "Résumé quotidien général de notifications",
                    ),
                    ("digest_for_switchtender", "Résumé quotidien des conseillers"),
                    (
                        "new_recommendations_digest",
                        "Résumé des nouvelles recommandations",
                    ),
                    (
                        "new_site_for_switchtender",
                        "Alerte conseillers d'un nouveau projet sur le territoire",
                    ),
                    ("sharing invitation", "Invitation à rejoindre un projet"),
                    (
                        "project_reminders_whats_up_digest",
                        "Où en êtes-vous ? (mail projet C)",
                    ),
                ],
                max_length=40,
            ),
        ),
    ]
