# Generated by Django 3.2.23 on 2024-01-09 13:43

from django.conf import settings
import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "communication",
            "0006_alter_emailtemplate_name_squashed_0009_alter_emailtemplate_name",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_on", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.CharField(max_length=65536, unique=True)),
                ("label", models.CharField(blank=True, max_length=2048)),
                (
                    "faked",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="If this sent was faked",
                    ),
                ),
                ("related_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "related_ct",
                    models.ForeignKey(
                        blank=True,
                        help_text="An non-user object related to this transaction",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
