# Generated by Django 4.2.13 on 2024-10-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0012_alter_emailtemplate_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="name",
            field=models.CharField(
                choices=[
                    ("project_received", "Projet bien reçu"),
                    ("project_accepted", "Projet accepté par l'équipe de modération"),
                    (
                        "digest_for_non_switchtender",
                        "Résumé quotidien général de notifications",
                    ),
                    ("digest_for_switchtender", "Résumé quotidien des conseillers"),
                    (
                        "new_recommendations_digest",
                        "Résumé des nouvelles recommandations",
                    ),
                    (
                        "new_site_for_switchtender",
                        "Alerte conseillers d'un nouveau projet sur le territoire",
                    ),
                    ("sharing_invitation", "Invitation à rejoindre un projet"),
                    (
                        "project_reminders_new_reco_digest",
                        "Rappel des nouvelles recommandations (mail projet B)",
                    ),
                    (
                        "project_reminders_whats_up_digest",
                        "Où en êtes-vous ? (mail projet C)",
                    ),
                    (
                        "project_added_to_new_site",
                        "Le Projet a été validé sur un nouveau portail",
                    ),
                ],
                max_length=40,
            ),
        ),
    ]
