# Generated by Django 4.2.19 on 2025-03-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0013_alter_emailtemplate_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="name",
            field=models.CharField(
                choices=[
                    ("project_received", "Dossier bien reçu"),
                    ("project_accepted", "Dossier accepté par l'équipe de modération"),
                    (
                        "digest_for_non_switchtender",
                        "Résumé quotidien général de notifications",
                    ),
                    ("digest_for_switchtender", "Résumé quotidien des conseillers"),
                    (
                        "new_recommendations_digest",
                        "Résumé des nouvelles recommandations",
                    ),
                    (
                        "new_site_for_switchtender",
                        "Alerte conseillers d'un nouveau dossier sur le territoire",
                    ),
                    ("sharing_invitation", "Invitation à rejoindre un dossier"),
                    (
                        "project_reminders_new_reco_digest",
                        "Rappel des nouvelles recommandations (mail dossier B)",
                    ),
                    (
                        "project_reminders_whats_up_digest",
                        "Où en êtes-vous ? (mail dossier C)",
                    ),
                    (
                        "project_added_to_new_site",
                        "Le Dossier a été validé sur un nouveau portail",
                    ),
                ],
                max_length=40,
            ),
        ),
    ]
