import pytest


@pytest.fixture(scope="module")
def ds_schema_sample():
    return {
        "id": "UHJvY2VkdXJlLTgwODky",
        "number": 80892,
        "title": "Demande de subvention au titre de la DETR ou de la DSIL 2024 en Moselle",
        "description": "Bienvenue sur le formulaire unique de demande de subvention au titre de la DETR et de la DSIL 2024. Il s'adresse aux communes et EPCI éligibles de Moselle qui souhaitent déposer une demande de financement au titre de ces deux dispositifs.\r\n\r\n",
        "state": "publiee",
        "declarative": None,
        "dateCreation": "2023-09-18T09:56:07+02:00",
        "datePublication": "2023-10-12T16:43:51+02:00",
        "dateDerniereModification": "2024-07-01T12:32:34+02:00",
        "dateDepublication": None,
        "dateFermeture": None,
        "notice": None,
        "deliberation": None,
        "demarcheURL": "https://www.demarches-simplifiees.fr/commencer/demande-de-subvention-detr-dsil-2024-en-moselle",
        "cadreJuridiqueURL": "https://www.legifrance.gouv.fr/eli/arrete/2018/8/21/CPAB1819920A/jo/texte/fr",
        "revision": {
            "id": "UHJvY2VkdXJlUmV2aXNpb24tMTE4NDY1",
            "datePublication": "2023-10-27T14:32:54+02:00",
            "champDescriptors": [
                {
                    "__typename": "ExplicationChampDescriptor",
                    "id": "Q2hhbXAtMjk5Njg5OA==",
                    "label": "Demandes de subventions DETR - DSIL 2024",
                    "description": "Ce formulaire est destiné aux collectivités de Moselle qui souhaitent déposer une demande de subvention au titre de la DETR ou de la DSIL en 2024. Votre demande sera automatiquement orientée vers la sous-préfecture compétente.\r\n\r\nLa date limite de dépôt des dossiers est fixée au 30 novembre 2023.\r\n\r\nDans le cadre de l'instruction des demandes, les projets sont orientés par les sous-préfets en lien avec la préfecture vers la dotation la plus adaptée (DETR ou DSIL).\r\n\r\nPour l'éligibilité des opérations, il convient de se référer à l’appel à projets 2024 commun à la DETR et à la DSIL, disponible à l'adresse suivante : https://www.moselle.gouv.fr/Actions-de-l-Etat/Collectivites-controle-de-legalite-et-finances-locales/Subventions\r\n\r\n",
                    "required": False,
                    "collapsibleExplanationEnabled": True,
                    "collapsibleExplanationText": "\r\nPour constituer votre dossier, les sections suivantes sont à compléter :\r\n\r\n-Informations sur le porteur de projet\r\n-Présentation de l'opération\r\n-Plan de financement prévisionnel\r\n-Finalisation du dossier\r\n\r\n\r\n\u003Cbr /\u003E\r\n\r\nVotre dossier est enregistré automatiquement après chaque modification. Vous pouvez à tout moment fermer la fenêtre et reprendre plus tard là où vous en étiez.",
                },
                {
                    "__typename": "YesNoChampDescriptor",
                    "id": "Q2hhbXAtMzYwNjYwNQ==",
                    "label": "Sollicitez-vous également un cofinancement au titre du dispositif Ambition Moselle ?",
                    "description": "Le présent formulaire ne vaut que pour les demandes de subventions  DETR/DSIL. Les demandes de subventions Ambition Moselle doivent être adressées directement auprès des services du département (selon modalités de dépôt en vigueur).",
                    "required": False,
                },
                {
                    "__typename": "HeaderSectionChampDescriptor",
                    "id": "Q2hhbXAtODgwNDAy",
                    "label": "Informations sur le porteur de projet",
                    "description": None,
                    "required": False,
                },
                {
                    "__typename": "ExplicationChampDescriptor",
                    "id": "Q2hhbXAtMjk0NTM2Mg==",
                    "label": "Identification de la collectivité porteuse du projet",
                    "description": "",
                    "required": False,
                    "collapsibleExplanationEnabled": False,
                    "collapsibleExplanationText": "",
                },
                {
                    "__typename": "DropDownListChampDescriptor",
                    "id": "Q2hhbXAtMTk3NzQ0NQ==",
                    "label": "Nature du porteur de projet",
                    "description": "Sauf cas particulier, les porteurs de projets éligibles à la DETR et à la DSIL sont les communes et les établissements publics de coopération intercommunale.",
                    "required": True,
                    "options": [
                        "Commune",
                        "EPCI",
                        "Pôle d'équilibre territorial et rural",
                        "Syndicat de communes",
                    ],
                    "otherOption": True,
                },
                {
                    "__typename": "DropDownListChampDescriptor",
                    "id": "Q2hhbXAtMzI3Njk1NA==",
                    "label": "Département et arrondissement du porteur de projet",
                    "description": "Votre dossier sera transmis à l'autorité compétente pour instruire votre dossier.",
                    "required": True,
                    "options": [
                        "57 - Moselle - arrondissement de Forbach-Boulay-Moselle",
                        "57 - Moselle - arrondissement de Metz",
                        "57 - Moselle - arrondissement de Sarrebourg-Château-Salins",
                        "57 - Moselle - arrondissement de Sarreguemines",
                        "57 - Moselle - arrondissement de Thionville",
                    ],
                    "otherOption": False,
                },
                {
                    "__typename": "DropDownListChampDescriptor",
                    "id": "Q2hhbXAtMjkzNDM2NA==",
                    "label": "Fonction du représentant légal",
                    "description": "La demande de subvention est présentée par le maire ou le président de l'établissement public de coopération intercommunale compétent (article R2334-22 du CGCT).",
                    "required": True,
                    "options": [
                        "Maire",
                        "Président d'EPCI",
                        "Président de syndicat intercommunal",
                    ],
                    "otherOption": True,
                },
                {
                    "__typename": "TextChampDescriptor",
                    "id": "Q2hhbXAtMjkzNDM2MA==",
                    "label": "Nom du représentant légal",
                    "description": "",
                    "required": True,
                },
                {
                    "__typename": "TextChampDescriptor",
                    "id": "Q2hhbXAtMjkzNDM2Mg==",
                    "label": "Prénom du représentant légal",
                    "description": "",
                    "required": True,
                },
                {
                    "__typename": "YesNoChampDescriptor",
                    "id": "Q2hhbXAtMjk5Nzg0MA==",
                    "label": "La maîtrise d'ouvrage de l'opération sera-t-elle déléguée ?",
                    "description": "Une collectivité peut bénéficier d’une subvention au titre de la DETR, de la DSIL afin de financer une opération pour laquelle elle a délégué la maîtrise d’ouvrage, à condition qu’elle justifie d’une participation financière à hauteur d’au moins 20% de la totalité des financements publics mobilisés. ",
                    "required": True,
                },
                {
                    "__typename": "SiretChampDescriptor",
                    "id": "Q2hhbXAtMjk0NTU5OA==",
                    "label": "Identification du maître d'ouvrage",
                    "description": "Merci d'indiquer le code SIRET de la personne morale délégataire de la maîtrise d'ouvrage.",
                    "required": True,
                },
                {
                    "__typename": "PieceJustificativeChampDescriptor",
                    "id": "Q2hhbXAtMzM0NDQ4MQ==",
                    "label": "Joindre la convention de délégation",
                    "description": "Convention signée par la collectivité déléguant la maîtrise d'ouvrage et l'entité délégataire.",
                    "required": True,
                    "fileTemplate": None,
                },
                {
                    "__typename": "ExplicationChampDescriptor",
                    "id": "Q2hhbXAtMTUwNjQwMQ==",
                    "label": "Identification de la personne chargée du suivi du dossier",
                    "description": "",
                    "required": False,
                    "collapsibleExplanationEnabled": False,
                    "collapsibleExplanationText": None,
                },
                {
                    "__typename": "TextChampDescriptor",
                    "id": "Q2hhbXAtMjkzNDM5MQ==",
                    "label": "Nom",
                    "description": "",
                    "required": True,
                },
                {
                    "__typename": "TextChampDescriptor",
                    "id": "Q2hhbXAtMjkzNDM5Mw==",
                    "label": "Prénom",
                    "description": "",
                    "required": True,
                },
                {
                    "__typename": "TextChampDescriptor",
                    "id": "Q2hhbXAtMjkzNDM5NA==",
                    "label": "Fonction",
                    "description": "",
                    "required": True,
                },
                {
                    "__typename": "PhoneChampDescriptor",
                    "id": "Q2hhbXAtMjkzNDQwMQ==",
                    "label": "Téléphone",
                    "description": "",
                    "required": True,
                },
                {
                    "__typename": "EmailChampDescriptor",
                    "id": "Q2hhbXAtMzYwNjk5NQ==",
                    "label": "Email",
                    "description": "",
                    "required": True,
                },
                {
                    "__typename": "HeaderSectionChampDescriptor",
                    "id": "Q2hhbXAtMjk3MTQxNw==",
                    "label": "Présentation de l'opération",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "ExplicationChampDescriptor",
                    "id": "Q2hhbXAtMzI5MzY1Mw==",
                    "label": "Description du projet",
                    "description": "",
                    "required": False,
                    "collapsibleExplanationEnabled": False,
                    "collapsibleExplanationText": None,
                },
                {
                    "__typename": "TextChampDescriptor",
                    "id": "Q2hhbXAtMjk3MTQ0NA==",
                    "label": "Intitulé du projet",
                    "description": "Description succincte et précise de l'opération pour laquelle vous demandez le soutien de l’État. Exemple : rénovation énergétique de l'école primaire, mise en accessibilité de la mairie, création d'une maison France Services.",
                    "required": True,
                },
                {
                    "__typename": "AddressChampDescriptor",
                    "id": "Q2hhbXAtMzAyMDUwMA==",
                    "label": "Adresse principale du projet",
                    "description": "Si possible, précisez une adresse précise, à défaut le nom de la commune qui accueille l'opération.",
                    "required": True,
                },
                {
                    "__typename": "PieceJustificativeChampDescriptor",
                    "id": "Q2hhbXAtMjk0NTY0NA==",
                    "label": "Délibération du conseil municipal ou de l'organe délibérant de l'EPCI",
                    "description": "Fournir la délibération du conseil municipal ou de l'organe délibérant de l'établissement public de coopération intercommunale adoptant l'opération et arrêtant ses modalités de financement.",
                    "required": False,
                    "fileTemplate": None,
                },
                {
                    "__typename": "PieceJustificativeChampDescriptor",
                    "id": "Q2hhbXAtMzI3Njk1Nw==",
                    "label": "Joindre un document de présentation de votre projet",
                    "description": "Ce document explicatif doit préciser l'objet de l'opération, les objectifs poursuivis, sa durée, le coût prévisionnel global ainsi que le montant de la subvention sollicitée.",
                    "required": False,
                    "fileTemplate": None,
                },
                {
                    "__typename": "YesNoChampDescriptor",
                    "id": "Q2hhbXAtMzI5MzU1Mw==",
                    "label": "Le projet d'investissement comprend-il des acquisitions immobilières ?",
                    "description": "",
                    "required": True,
                },
                {
                    "__typename": "PieceJustificativeChampDescriptor",
                    "id": "Q2hhbXAtMzI5MzU1Mg==",
                    "label": "Joindre un plan de situation et/ou le plan cadastral",
                    "description": "",
                    "required": True,
                    "fileTemplate": None,
                },
                {
                    "__typename": "PieceJustificativeChampDescriptor",
                    "id": "Q2hhbXAtMzI5MzU1NA==",
                    "label": "Si l’acquisition du terrain est effective, joindre le titre de propriété et la justification de son caractère onéreux.",
                    "description": "",
                    "required": False,
                    "fileTemplate": None,
                },
                {
                    "__typename": "YesNoChampDescriptor",
                    "id": "Q2hhbXAtMzI5MzU1NQ==",
                    "label": "Le projet d'investissement comprend-il des travaux ?",
                    "description": "En cas de travaux, vous devez impérativement joindre les justificatifs suivants : situation juridique des terrains et des immeubles, plan de situation et plan de masse des travaux, programme détaillé des travaux et dossier d'avant projet définitif.  **Attention : le projet doit également respecter les dispositions du code de l'urbanisme (notamment l'obligation de déclaration préalable, permis de construire et la demande d'un avis ABF pour les travaux à proximité de monuments classés).**",
                    "required": True,
                },
                {
                    "__typename": "PieceJustificativeChampDescriptor",
                    "id": "Q2hhbXAtMzI5MzU1Ng==",
                    "label": "Justificatif travaux 01 - Situation juridique des terrains et immeubles",
                    "description": "Joindre un document précisant la situation juridique des terrains et immeubles et établissant que le demandeur a ou aura la libre disposition de ceux-ci.",
                    "required": False,
                    "fileTemplate": None,
                },
                {
                    "__typename": "PieceJustificativeChampDescriptor",
                    "id": "Q2hhbXAtMzMzNTgyNQ==",
                    "label": "Justificatif travaux 02 - Plan de situation et plan de masse des travaux",
                    "description": "",
                    "required": False,
                    "fileTemplate": None,
                },
                {
                    "__typename": "PieceJustificativeChampDescriptor",
                    "id": "Q2hhbXAtMzMzNTgyNg==",
                    "label": "Justificatif travaux 03 - Programme détaillé des travaux",
                    "description": "",
                    "required": False,
                    "fileTemplate": None,
                },
                {
                    "__typename": "PieceJustificativeChampDescriptor",
                    "id": "Q2hhbXAtMzMzNTgyNw==",
                    "label": "Justificatif travaux 04 - Dossier d'avant-projet définitif",
                    "description": "",
                    "required": False,
                    "fileTemplate": None,
                },
                {
                    "__typename": "MultipleDropDownListChampDescriptor",
                    "id": "Q2hhbXAtMjk0NTQyMw==",
                    "label": "Zonage spécifique : le projet est il situé dans l'une des zones suivantes ?",
                    "description": "Sélectionner un ou plusieurs zonages spécifiques.",
                    "required": True,
                    "options": [
                        "Aucun zonage",
                        "Quartiers prioritaires de la politique de la Ville (QPV)",
                        "Nouveau programme de rénovation urbaine (NPNRU)",
                        "ÉcoQuartier",
                        "Territoires Engagées pour la Nature (TEN)",
                        "Zones de revitalisation rurale (ZRR)",
                        "Territoires d'industrie (TI)",
                        "Zone de protection du patrimoine architectural, urbain et paysager (ZPPAUP)",
                        "Aire de mise en valeur de l'architecture et du patrimoine (AVAP)",
                        "Site patrimonial remarquable (SPR)",
                        "Avenir montagne",
                    ],
                },
                {
                    "__typename": "MultipleDropDownListChampDescriptor",
                    "id": "Q2hhbXAtMjk0NzQzNQ==",
                    "label": "Contractualisation : le projet est-il inscrit dans un ou plusieurs contrats avec l'Etat ?",
                    "description": "Indiquer si le projet s'inscrit dans un contrat signé entre la collectivité et l’État. Exemple : projet inscrit dans un contrat de relance et de transition écologique (CRTE), conventions Action Cœur de Ville et Petites villes de Demain, etc.",
                    "required": False,
                    "options": [
                        "Pacte territorial de relance et de transition écologique (PTRTE)",
                        "Action Cœur de Ville (ACV)",
                        "Petites Villes de Demain (PVD)",
                        "Contrat de ruralité",
                        "Contrat de plan État-Région (CPER)",
                        "Contrat de Convergence et de Transformation (CCT)",
                        "Opération de revitalisation du territoire (ORT)",
                        "Opération d'intérêt national (OIN)",
                        "Opération programmée d'amélioration de l'habitat (OPAH)",
                        "Projet partenarial d’aménagement (PPA)",
                        "Autre contrat",
                    ],
                },
                {
                    "__typename": "TextChampDescriptor",
                    "id": "Q2hhbXAtMzM0MjIxNg==",
                    "label": "Autre contrat : précisez le contrat concerné",
                    "description": "",
                    "required": True,
                },
                {
                    "__typename": "ExplicationChampDescriptor",
                    "id": "Q2hhbXAtMzI5MzY1NA==",
                    "label": "Impact environnemental du projet",
                    "description": "",
                    "required": False,
                    "collapsibleExplanationEnabled": False,
                    "collapsibleExplanationText": None,
                },
                {
                    "__typename": "YesNoChampDescriptor",
                    "id": "Q2hhbXAtMzQ2NzY5OQ==",
                    "label": "Le projet concourt-il aux enjeux de la transition écologique ?",
                    "description": "",
                    "required": True,
                },
                {
                    "__typename": "MultipleDropDownListChampDescriptor",
                    "id": "Q2hhbXAtMzI4MDE4Mw==",
                    "label": "Si oui, indiquer quels sont les objectifs environnementaux impactés favorablement.",
                    "description": "",
                    "required": True,
                    "options": [
                        "Lutte contre le changement climatique",
                        "Adaptation au changement climatique et prévention des risques naturels",
                        "Amélioration de la gestion de la ressource en eau",
                        "Amélioration de la gestion des déchets et prévention des risques technologiques",
                        "Lutte contre les pollutions",
                        "Protection de la biodiversité et des espaces naturels, agricoles et sylvicoles",
                    ],
                },
                {
                    "__typename": "MultipleDropDownListChampDescriptor",
                    "id": "Q2hhbXAtMzU2MTUxMw==",
                    "label": "Lutte contre le changement climatique",
                    "description": "",
                    "required": True,
                    "options": ["Favorable", "Défavorable", "Neutre"],
                },
                {
                    "__typename": "MultipleDropDownListChampDescriptor",
                    "id": "Q2hhbXAtMzU2MTUxNA==",
                    "label": "Adaptation au changement climatique et prévention des risques naturels",
                    "description": "",
                    "required": True,
                    "options": ["Favorable", "Défavorable", "Neutre"],
                },
                {
                    "__typename": "MultipleDropDownListChampDescriptor",
                    "id": "Q2hhbXAtMzU2MTUxNQ==",
                    "label": "Amélioration de la gestion de la ressource en eau",
                    "description": "",
                    "required": True,
                    "options": ["Favorable", "Défavorable", "Neutre"],
                },
                {
                    "__typename": "MultipleDropDownListChampDescriptor",
                    "id": "Q2hhbXAtMzU2MTUxOQ==",
                    "label": "Amélioration de la gestion des déchets et prévention des risques technologiques",
                    "description": "",
                    "required": True,
                    "options": ["Favorable", "Défavorable", "Neutre"],
                },
                {
                    "__typename": "MultipleDropDownListChampDescriptor",
                    "id": "Q2hhbXAtMzU2MTUyMg==",
                    "label": "Lutte contre les pollutions",
                    "description": "",
                    "required": True,
                    "options": ["Favorable", "Défavorable", "Neutre"],
                },
                {
                    "__typename": "MultipleDropDownListChampDescriptor",
                    "id": "Q2hhbXAtMzU2MTUyNA==",
                    "label": "Protection de la biodiversité et des espaces naturels, agricoles et sylvicoles",
                    "description": "",
                    "required": True,
                    "options": ["Favorable", "Défavorable", "Neutre"],
                },
                {
                    "__typename": "TextareaChampDescriptor",
                    "id": "Q2hhbXAtMzQ2NzcwMA==",
                    "label": "Justifier en quelques mots.",
                    "description": "",
                    "required": True,
                },
                {
                    "__typename": "YesNoChampDescriptor",
                    "id": "Q2hhbXAtMzI5MzY1NQ==",
                    "label": "Le projet implique-t-il une artificialisation des sols ?",
                    "description": "L'artificialisation des sols désigne la transformation d’un espace naturel en terrain imperméabilisé.",
                    "required": True,
                },
                {
                    "__typename": "ExplicationChampDescriptor",
                    "id": "Q2hhbXAtMzU0MDgzNw==",
                    "label": "Pour les projets de rénovation énergétique des bâtiments publics, veuillez remplir les champs suivants :",
                    "description": "",
                    "required": False,
                    "collapsibleExplanationEnabled": False,
                    "collapsibleExplanationText": None,
                },
                {
                    "__typename": "IntegerNumberChampDescriptor",
                    "id": "Q2hhbXAtMzU0MDgzOQ==",
                    "label": "Surface de bâtiment concernée par l’opération en m²",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "IntegerNumberChampDescriptor",
                    "id": "Q2hhbXAtMzU0MDg1OQ==",
                    "label": "Nombre d’usagers (ou moyenne)",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "DropDownListChampDescriptor",
                    "id": "Q2hhbXAtMzU0MTA1MA==",
                    "label": "Système de chauffage avant travaux",
                    "description": "",
                    "required": False,
                    "options": [
                        "Chaudière fioul",
                        "Chaudière gaz",
                        "Pompe à chaleur",
                        "Chaudière bois ou biomasse",
                        "Poêle à bois ou biomasse",
                        "Chauffage électrique à effet Joule",
                    ],
                    "otherOption": False,
                },
                {
                    "__typename": "DropDownListChampDescriptor",
                    "id": "Q2hhbXAtMzU0MTA1MQ==",
                    "label": "Système de chauffage après travaux",
                    "description": "",
                    "required": False,
                    "options": [
                        "Chaudière fioul",
                        "Chaudière gaz",
                        "Pompe à chaleur",
                        "Chaudière bois ou biomasse",
                        "Poêle à bois ou biomasse",
                        "Chauffage électrique à effet Joule",
                    ],
                    "otherOption": True,
                },
                {
                    "__typename": "IntegerNumberChampDescriptor",
                    "id": "Q2hhbXAtMzU0MDg2Mw==",
                    "label": "Consommation énergétique avant travaux (en kWhEF/an)",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "MultipleDropDownListChampDescriptor",
                    "id": "Q2hhbXAtMzU2NDg1Mw==",
                    "label": "Etiquette de consommation d'énergie avant travaux : A à G",
                    "description": "",
                    "required": False,
                    "options": ["A", "B", "C", "D", "E", "F", "G"],
                },
                {
                    "__typename": "IntegerNumberChampDescriptor",
                    "id": "Q2hhbXAtMzU0MDg2MQ==",
                    "label": "Consommation énergétique après travaux (en kWhEF/an)",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "MultipleDropDownListChampDescriptor",
                    "id": "Q2hhbXAtMzU2MjE0OA==",
                    "label": "Etiquette de consommation d'énergie après travaux : A à G",
                    "description": "",
                    "required": False,
                    "options": ["A", "B", "C", "D", "E", "F", "G"],
                },
                {
                    "__typename": "IntegerNumberChampDescriptor",
                    "id": "Q2hhbXAtMzU2MTY2Nw==",
                    "label": "Ratio de consommation énergétique du bâtiment après travaux (en kWEF/m2)",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "IntegerNumberChampDescriptor",
                    "id": "Q2hhbXAtMzU0MDg2NA==",
                    "label": "Gain énergétique estimé (en %)",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "TextChampDescriptor",
                    "id": "Q2hhbXAtMzU0MDg2NQ==",
                    "label": "Emissions GES initiales avant travaux (en TeqCO2/an)",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "TextChampDescriptor",
                    "id": "Q2hhbXAtMzU0MDg2Ng==",
                    "label": "Emissions GES initiales après travaux (en TeqCO2/an)",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "MultipleDropDownListChampDescriptor",
                    "id": "Q2hhbXAtMzU2MjE0OQ==",
                    "label": "Etiquette d'émission de gaz à effet de serre après travaux : A à G",
                    "description": "",
                    "required": False,
                    "options": ["A", "B", "C", "D", "E", "F", "G"],
                },
                {
                    "__typename": "ExplicationChampDescriptor",
                    "id": "Q2hhbXAtMzU0MTIyNQ==",
                    "label": "Pour les projets d'infrastructures favorisant la mobilité, veuillez remplir les champs suivants :",
                    "description": "",
                    "required": False,
                    "collapsibleExplanationEnabled": False,
                    "collapsibleExplanationText": None,
                },
                {
                    "__typename": "IntegerNumberChampDescriptor",
                    "id": "Q2hhbXAtMzU0MTIyNw==",
                    "label": "Réduction des émissions de gaz à effet de serre (GES)",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "IntegerNumberChampDescriptor",
                    "id": "Q2hhbXAtMzU0MTIzMA==",
                    "label": "Baisse des émissions de GES (en %)",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "IntegerNumberChampDescriptor",
                    "id": "Q2hhbXAtMzU0MTIzNQ==",
                    "label": "Nombre de véhicules thermiques en moins (estimation)",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "ExplicationChampDescriptor",
                    "id": "Q2hhbXAtMzUyMzI3Mg==",
                    "label": "Impact du projet sur l'emploi",
                    "description": "",
                    "required": False,
                    "collapsibleExplanationEnabled": False,
                    "collapsibleExplanationText": None,
                },
                {
                    "__typename": "YesNoChampDescriptor",
                    "id": "Q2hhbXAtMzUyMzI3Mw==",
                    "label": "Envisagez-vous de recouvrir à la mise en oeuvre de clauses de promotion de l’emploi, dite « clauses sociales » dans les marchés que vous passerez pour la réalisation de votre projet ?",
                    "description": "Pour les demandes de subventions supérieures à 100 000 euros, l'insertion de clauses sociales au sein des marchés publics de réalisation de l'opération est obligatoire.",
                    "required": True,
                },
                {
                    "__typename": "TextChampDescriptor",
                    "id": "Q2hhbXAtMzUyMzI3OQ==",
                    "label": "Si oui, merci de préciser le nombre d’heures d’insertion envisagées (si définies) :",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "YesNoChampDescriptor",
                    "id": "Q2hhbXAtMzUyMzUxMw==",
                    "label": "Avez-vous déjà contacté un facilitateur ?",
                    "description": "",
                    "required": True,
                },
                {
                    "__typename": "ExplicationChampDescriptor",
                    "id": "Q2hhbXAtMjk0NTcxMA==",
                    "label": "Dates prévisionnelles de réalisation du projet",
                    "description": "",
                    "required": False,
                    "collapsibleExplanationEnabled": False,
                    "collapsibleExplanationText": None,
                },
                {
                    "__typename": "DateChampDescriptor",
                    "id": "Q2hhbXAtMjk0NTcxMg==",
                    "label": "Date de commencement de l'opération",
                    "description": " **Si cette date n'est pas connue précisément, indiquer une date prévisionnelle.**",
                    "required": True,
                },
                {
                    "__typename": "DateChampDescriptor",
                    "id": "Q2hhbXAtMjk0NTcxNA==",
                    "label": "Date prévisionnelle d'achèvement de l'opération",
                    "description": "En application des dispositions de [l’article R2334-29 du CGCT](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006397216), le bénéficiaire dispose d'un délai de quatre ans à compter de la date de déclaration du début d'exécution pour achever l'opération.",
                    "required": True,
                },
                {
                    "__typename": "HeaderSectionChampDescriptor",
                    "id": "Q2hhbXAtMjk0NTQzOA==",
                    "label": "Plan de financement prévisionnel",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "ExplicationChampDescriptor",
                    "id": "Q2hhbXAtMzM1NDI5MA==",
                    "label": "Dépenses et recettes prévisionnelles",
                    "description": "",
                    "required": False,
                    "collapsibleExplanationEnabled": False,
                    "collapsibleExplanationText": None,
                },
                {
                    "__typename": "DecimalNumberChampDescriptor",
                    "id": "Q2hhbXAtMjk0NzQzNw==",
                    "label": "Coût total de l'opération (en euros HT)",
                    "description": "Indiquer le montant prévisionnel HORS TAXES en euros des dépenses de l'opération. Seules les dépenses inscrites en section d'investissement sont éligibles.",
                    "required": True,
                },
                {
                    "__typename": "PieceJustificativeChampDescriptor",
                    "id": "Q2hhbXAtMzMzNTUxOQ==",
                    "label": "Justificatifs des dépenses prévisionnelles",
                    "description": "Joindre un devis descriptif détaillant les dépenses ([consultez la source juridique](https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000416510)).",
                    "required": True,
                    "fileTemplate": None,
                },
                {
                    "__typename": "YesNoChampDescriptor",
                    "id": "Q2hhbXAtMzM1ODI1MA==",
                    "label": "Le projet va-t-il générer des recettes ?",
                    "description": "Loyers, produits de cessions, etc.",
                    "required": True,
                },
                {
                    "__typename": "TextChampDescriptor",
                    "id": "Q2hhbXAtMzYwOTEzMw==",
                    "label": "Si oui, préciser la nature des recettes ( Ventes, loyers, redevance...)",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "DecimalNumberChampDescriptor",
                    "id": "Q2hhbXAtMzYwOTE4MA==",
                    "label": "Montant annuel escompté",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "PieceJustificativeChampDescriptor",
                    "id": "Q2hhbXAtMzM1NDM1OA==",
                    "label": "Plan de financement détaillé",
                    "description": "L'utilisation du modèle joint est obligatoire.",
                    "required": True,
                    "fileTemplate": {
                        "__typename": "File",
                        "filename": "Modèle plan de financement.ods",
                        "contentType": "application/vnd.oasis.opendocument.spreadsheet",
                        "checksum": "H0IdHKUmFU8yHyD9M4SUsQ==",
                        "byteSize": "31285",
                        "url": "https://static.demarches-simplifiees.fr:443/v1/AUTH_db3cbfc79c914f87b192ff7c6bb176f0/ds_activestorage_backup/2023/10/06/3j/3jx9RzPrQAQwyepB78tWav5QNKfS?temp_url_sig=ff1bdee3d966b71dcaeefd58eed16505576c6cfb&temp_url_expires=1719854763&filename=Mod%C3%A8le%20plan%20de%20financement.ods",
                        "createdAt": "2023-10-06T18:20:47+02:00",
                    },
                },
                {
                    "__typename": "ExplicationChampDescriptor",
                    "id": "Q2hhbXAtMzI3OTcwOA==",
                    "label": "Aides à l'investissement sollicitées",
                    "description": "Dans le cadre de l'instruction des demandes, les projets sont orientés par les sous-préfets en lien avec la préfecture vers la dotation la plus adaptée (DETR ou DSIL).\r\n\r\nLe cahier des charges DETR et la liste des opérations éligibles à la DSIL sont disponibles à l'adresse suivante : https://www.moselle.gouv.fr/Actions-de-l-Etat/Collectivites-controle-de-legalite-et-finances-locales/Subventions",
                    "required": False,
                    "collapsibleExplanationEnabled": False,
                    "collapsibleExplanationText": None,
                },
                {
                    "__typename": "YesNoChampDescriptor",
                    "id": "Q2hhbXAtMzM0MjIxOA==",
                    "label": "Avez-vous déjà présenté cette opération au titre de la campagnes DETR/DSIL 2023 ?",
                    "description": "Si votre demande concerne une opération pour laquelle une demande a déjà été déposée au titre de la DETR et/ou de la DSIL en 2023 et que l'opération n'a pas été modifiée depuis, vous pouvez demander une nouvelle instruction de ce dossier au titre de l'exercice 2024.",
                    "required": True,
                },
                {
                    "__typename": "TextChampDescriptor",
                    "id": "Q2hhbXAtMzM0MjIyMA==",
                    "label": "Précisez le numéro du dossier déposé antérieurement",
                    "description": "Le numéro de dossier n'est pas nécessaire en cas de dépôt de la demande en 2023.",
                    "required": False,
                },
                {
                    "__typename": "DecimalNumberChampDescriptor",
                    "id": "Q2hhbXAtMjk3NzM3NQ==",
                    "label": "Montant de l'aide demandée",
                    "description": " [Conformément à l'article L1111-10 du CGCT](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000041411642/), vous devez assurer une participation minimale au financement de ce projet fixée à 20 % du montant total des financements apportés par des personnes publiques à ce projet.",
                    "required": True,
                },
                {
                    "__typename": "TextChampDescriptor",
                    "id": "Q2hhbXAtMzYwNzUyNw==",
                    "label": "Taux de l'aide demandée",
                    "description": "Indiquer le taux de la subvention sollicitée.",
                    "required": True,
                },
                {
                    "__typename": "YesNoChampDescriptor",
                    "id": "Q2hhbXAtMzYwODYwOA==",
                    "label": "Avez-vous déposé ou envisagez-vous de déposer une demande de subvention auprès d'un autre financeur public ?",
                    "description": "",
                    "required": True,
                },
                {
                    "__typename": "RepetitionChampDescriptor",
                    "id": "Q2hhbXAtMzYwODYxMQ==",
                    "label": "Autres financements sollicités",
                    "description": "",
                    "required": False,
                    "champDescriptors": [
                        {
                            "__typename": "TextChampDescriptor",
                            "id": "Q2hhbXAtMzYwODYxMg==",
                            "label": "Identité du financeur",
                            "description": "",
                            "required": False,
                        },
                        {
                            "__typename": "DecimalNumberChampDescriptor",
                            "id": "Q2hhbXAtMzYwODYzNw==",
                            "label": "Montant prévisionnel de la subvention",
                            "description": "",
                            "required": False,
                        },
                        {
                            "__typename": "CheckboxChampDescriptor",
                            "id": "Q2hhbXAtMzYwOTE4Mw==",
                            "label": "À solliciter",
                            "description": "",
                            "required": False,
                        },
                        {
                            "__typename": "CheckboxChampDescriptor",
                            "id": "Q2hhbXAtMzYwOTE4NQ==",
                            "label": "Sollicitée",
                            "description": "",
                            "required": False,
                        },
                        {
                            "__typename": "PieceJustificativeChampDescriptor",
                            "id": "Q2hhbXAtMzYwOTE4Nw==",
                            "label": "Lettre de demande de subvention",
                            "description": "",
                            "required": False,
                            "fileTemplate": None,
                        },
                        {
                            "__typename": "CheckboxChampDescriptor",
                            "id": "Q2hhbXAtMzYwOTE4Ng==",
                            "label": "Attribuée",
                            "description": "",
                            "required": False,
                        },
                        {
                            "__typename": "PieceJustificativeChampDescriptor",
                            "id": "Q2hhbXAtMzYwOTE4OA==",
                            "label": "Décision attributive de subvention",
                            "description": "",
                            "required": False,
                            "fileTemplate": None,
                        },
                    ],
                },
                {
                    "__typename": "YesNoChampDescriptor",
                    "id": "Q2hhbXAtMzYwODc1NA==",
                    "label": "Avez-vous déposé ou envisagez-vous de déposer une demande d'aide financière auprès d'un financeur privé ? (CAF, Fondation du Patrimoine, mécénat, fédérations sportives…) ?",
                    "description": "",
                    "required": True,
                },
                {
                    "__typename": "RepetitionChampDescriptor",
                    "id": "Q2hhbXAtMzYwODc1Ng==",
                    "label": "Autres financements sollicités",
                    "description": "",
                    "required": False,
                    "champDescriptors": [
                        {
                            "__typename": "TextChampDescriptor",
                            "id": "Q2hhbXAtMzYwODc1OA==",
                            "label": "Identité du financeur",
                            "description": "",
                            "required": False,
                        },
                        {
                            "__typename": "DecimalNumberChampDescriptor",
                            "id": "Q2hhbXAtMzYwODc1OQ==",
                            "label": "Montant prévisionnel de l'aide",
                            "description": "",
                            "required": False,
                        },
                        {
                            "__typename": "CheckboxChampDescriptor",
                            "id": "Q2hhbXAtMzYxMDA4Ng==",
                            "label": "À solliciter",
                            "description": "",
                            "required": False,
                        },
                        {
                            "__typename": "CheckboxChampDescriptor",
                            "id": "Q2hhbXAtMzYxMDA4Nw==",
                            "label": "Sollicitée",
                            "description": "",
                            "required": False,
                        },
                        {
                            "__typename": "PieceJustificativeChampDescriptor",
                            "id": "Q2hhbXAtMzYxMDA5MA==",
                            "label": "Lettre de demande de subvention",
                            "description": "",
                            "required": False,
                            "fileTemplate": None,
                        },
                        {
                            "__typename": "CheckboxChampDescriptor",
                            "id": "Q2hhbXAtMzYxMDExNA==",
                            "label": "Attribuée",
                            "description": "",
                            "required": False,
                        },
                        {
                            "__typename": "PieceJustificativeChampDescriptor",
                            "id": "Q2hhbXAtMzYxMDE0Ng==",
                            "label": "Décision attributive de subvention",
                            "description": "",
                            "required": False,
                            "fileTemplate": None,
                        },
                    ],
                },
                {
                    "__typename": "YesNoChampDescriptor",
                    "id": "Q2hhbXAtMzMzNTYxMg==",
                    "label": "Présentez-vous une autre opération au titre de la DETR/DSIL 2024 ?",
                    "description": 'Cochez "oui" si vous comptez ou avez déjà déposé une demande de subvention au titre de la DETR ou de la DSIL 2024 pour une autre opération d\'investissement.',
                    "required": True,
                },
                {
                    "__typename": "IntegerNumberChampDescriptor",
                    "id": "Q2hhbXAtMzMzNTY1MA==",
                    "label": "Si oui, précisez le niveau de priorité de ce dossier.",
                    "description": "Indiquer le rang de classement du projet par rapport aux autres dossiers que vous souhaitez déposer en 2024.",
                    "required": True,
                },
                {
                    "__typename": "HeaderSectionChampDescriptor",
                    "id": "Q2hhbXAtMzI3OTg2Mg==",
                    "label": "Finalisation du dossier",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "ExplicationChampDescriptor",
                    "id": "Q2hhbXAtMzI5MzU1Nw==",
                    "label": "Pièces complémentaires",
                    "description": "",
                    "required": False,
                    "collapsibleExplanationEnabled": False,
                    "collapsibleExplanationText": None,
                },
                {
                    "__typename": "RepetitionChampDescriptor",
                    "id": "Q2hhbXAtMjk3NzYxOA==",
                    "label": "Pièces complémentaires",
                    "description": "Inclure ici tous les documents utiles à l'instruction de votre demande, notamment :\r\n* Documents d'urbanisme (déclaration préalable, permis de construire)\r\n* Devis\r\n* Justificatifs des autres financements publics obtenus\r\n\r\nPour les projets de rénovation énergétique des bâtiments, inclure les documents suivant :\r\n* Audit ou diagnostic énergétique\r\n\r\nPour les projets de pistes cyclables, inclure les documents suivant :\r\n* plan du projet avec les itinéraires existants et à venir (le cas échant) à proximité\r\n* plan détaillé du projet avec des informations sur la largeur de l'infrastructure et le traitement des intersections\r\n* les précisions sur la typologie du projet : bande cyclable/piste cyclable/voie verte avec les linéaires associés à chaque portion et le linéaire global du projet\r\n* dans le cas où la circulation cycliste partage la voirie avec des véhicules, préciser les trafic observé sur la voirie",
                    "required": False,
                    "champDescriptors": [
                        {
                            "__typename": "PieceJustificativeChampDescriptor",
                            "id": "Q2hhbXAtMzU2NDM4Nw==",
                            "label": "Nouveau champ",
                            "description": "",
                            "required": False,
                            "fileTemplate": None,
                        }
                    ],
                },
                {
                    "__typename": "TextareaChampDescriptor",
                    "id": "Q2hhbXAtMzM1NDI0NA==",
                    "label": "Commentaire libre",
                    "description": "Indiquez ici tout autre information utile à l'instruction du dossier.",
                    "required": False,
                },
                {
                    "__typename": "ExplicationChampDescriptor",
                    "id": "Q2hhbXAtMzExODQ5Nw==",
                    "label": "Engagements du porteur de projet",
                    "description": "",
                    "required": False,
                    "collapsibleExplanationEnabled": False,
                    "collapsibleExplanationText": None,
                },
                {
                    "__typename": "CheckboxChampDescriptor",
                    "id": "Q2hhbXAtMzI3ODI2NA==",
                    "label": "Engagement n°1 - obligation d'information en cas de modification du projet",
                    "description": "En cochant la case, le demandeur s'engage à informer par écrit et sans délais la préfecture de département ou la sous-préfecture de son arrondissement si l'opération est annulée, si le coût de l'opération est révisé à la hausse ou à la baisse ou si l'opération est reportée.",
                    "required": True,
                },
                {
                    "__typename": "CheckboxChampDescriptor",
                    "id": "Q2hhbXAtMzI3ODI3Mw==",
                    "label": "Engagement n°2 - Obligation de publication du plan de financement",
                    "description": "En cochant la case, le demandeur s'engage à respecter l'obligation de publication de son plan de financement régie par les articles L. 1111-11 et D. 1111-8 du Code général des collectivités territoriales.",
                    "required": True,
                },
                {
                    "__typename": "CheckboxChampDescriptor",
                    "id": "Q2hhbXAtMzI3ODI2Nw==",
                    "label": "Engagement n°3 - Exactitude des informations",
                    "description": "En cochant la case, le demandeur atteste sur l'honneur l'exactitude des informations renseignées dans ce formulaire.",
                    "required": True,
                },
                {
                    "__typename": "CheckboxChampDescriptor",
                    "id": "Q2hhbXAtMzYwODM5Nw==",
                    "label": "Engagement n°4 - Attestation de non commencement",
                    "description": "En cochant la case, le demandeur atteste sur l'honneur que l’opération décrite ci-dessus, faisant l’objet d’une demande de subvention, n’a pas connu de commencement d’exécution (signature du premier acte juridique tel que les actes d’engagement des marchés ou signature d’un bon de commande).",
                    "required": True,
                },
                {
                    "__typename": "ExplicationChampDescriptor",
                    "id": "Q2hhbXAtMzI3ODI3OQ==",
                    "label": "Vous êtes sur le point de déposer votre dossier",
                    "description": "Le dépôt du dossier s’effectue en cliquant sur le bouton bleu en bas à droite de la présente page. L'opération peut prendre plusieurs minutes. Il n'est pas utile de cliquer plusieurs fois sur le bouton ou de rafraichir la page. Le dépôt du dossier et sa réception par les services de l’État vous seront confirmés automatiquement par courriel, à l'adresse renseignée lors de la création de votre compte \"Démarches simplifiées\".",
                    "required": False,
                    "collapsibleExplanationEnabled": False,
                    "collapsibleExplanationText": None,
                },
            ],
            "annotationDescriptors": [
                {
                    "__typename": "ExplicationChampDescriptor",
                    "id": "Q2hhbXAtMjk4MjQ3OQ==",
                    "label": "Partie réservée au service responsable de l’instruction de la DETR et/ou DSIL",
                    "description": "",
                    "required": False,
                    "collapsibleExplanationEnabled": False,
                    "collapsibleExplanationText": None,
                },
                {
                    "__typename": "TextChampDescriptor",
                    "id": "Q2hhbXAtMzM1NDYzNA==",
                    "label": "Contact de l'agent instructeur à indiquer au demandeur",
                    "description": "S'il est renseigné, ce champ sera ajouté aux courriels de notification envoyés lors du passage en instruction du dossier puis lors de son acceptation, de son classement sans suite ou de son refus. Ex : Prénom NOM, tel : 01 xx xx xx xx",
                    "required": False,
                },
                {
                    "__typename": "TextareaChampDescriptor",
                    "id": "Q2hhbXAtMjk3NjEzMA==",
                    "label": "Champ libre pour le service instructeur",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "RepetitionChampDescriptor",
                    "id": "Q2hhbXAtMzEzNjg0Nw==",
                    "label": "Autres documents utiles à l'instruction",
                    "description": "",
                    "required": False,
                    "champDescriptors": [
                        {
                            "__typename": "PieceJustificativeChampDescriptor",
                            "id": "Q2hhbXAtMzI4ODg1NA==",
                            "label": "Pièce-jointe complémentaire",
                            "description": "",
                            "required": False,
                            "fileTemplate": None,
                        }
                    ],
                },
                {
                    "__typename": "ExplicationChampDescriptor",
                    "id": "Q2hhbXAtMzM3MDQ3OA==",
                    "label": "Partie à compléter en cas de programmation du dossier",
                    "description": "",
                    "required": False,
                    "collapsibleExplanationEnabled": False,
                    "collapsibleExplanationText": None,
                },
                {
                    "__typename": "DropDownListChampDescriptor",
                    "id": "Q2hhbXAtMzAyMDUxMw==",
                    "label": "Imputation budgétaire - Choix de la dotation",
                    "description": "Préciser la ligne budgétaire vers laquelle le projet doit être orienté.",
                    "required": False,
                    "options": ["DETR", "DSIL"],
                    "otherOption": True,
                },
                {
                    "__typename": "CheckboxChampDescriptor",
                    "id": "Q2hhbXAtMzMzNjEwMA==",
                    "label": "Projet concourant à la transition écologique au sens budget vert",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "CheckboxChampDescriptor",
                    "id": "Q2hhbXAtMzM3MDcwMg==",
                    "label": "Projet situé en QPV",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "CheckboxChampDescriptor",
                    "id": "Q2hhbXAtMzM3MDY5MQ==",
                    "label": "Projet rattaché à un CRTE",
                    "description": "",
                    "required": False,
                },
                {
                    "__typename": "DecimalNumberChampDescriptor",
                    "id": "Q2hhbXAtMTk5MDI2Ng==",
                    "label": "Montant des dépenses éligibles retenues (€)",
                    "description": "Montant total des dépenses éligibles retenues à faire figurer sur l'arrêté préfectoral notifiant la décision de financement.",
                    "required": False,
                },
                {
                    "__typename": "DecimalNumberChampDescriptor",
                    "id": "Q2hhbXAtMjk4MjUwMA==",
                    "label": "Montant définitif de la subvention (€)",
                    "description": "Montant de la subvention à faire figurer sur l'arrêté préfectoral notifiant la décision de financement.",
                    "required": False,
                },
                {
                    "__typename": "DecimalNumberChampDescriptor",
                    "id": "Q2hhbXAtMzI4ODg1Mw==",
                    "label": "Taux de subvention (%)",
                    "description": "Le taux de subvention à faire figurer sur l'arrêté préfectoral notifiant la décision de financement. \r\nSources juridiques : articles [L. 1111-10](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000041411642/) et [R.2334-27](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044166963) CGCT.",
                    "required": False,
                },
                {
                    "__typename": "ExplicationChampDescriptor",
                    "id": "Q2hhbXAtMzQ2NDA1OQ==",
                    "label": "Pour plus d'information sur les annotations privées",
                    "description": "Contactez le bureau des concours financiers de l'Etat à l'adresse dgc-gestion-dotations@dgcl.gouv.fr",
                    "required": False,
                    "collapsibleExplanationEnabled": False,
                    "collapsibleExplanationText": None,
                },
            ],
        },
    }
