# Generated by Django 5.1.14 on 2025-12-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("invites", "0003_alter_invite_role"),
        ("invites", "0004_alter_invite_unique_together"),
        ("invites", "0005_alter_invite_role"),
    ]

    dependencies = [
        ("invites", "0002_auto_20220505_0957"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="role",
            field=models.CharField(
                choices=[
                    ("COLLABORATOR", "Participant·e"),
                    ("SWITCHTENDER", "Conseiller·e"),
                ],
                default="COLLABORATOR",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invite",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="invite",
            name="role",
            field=models.CharField(
                choices=[
                    ("COLLABORATOR", "Participant·e"),
                    ("SWITCHTENDER", "Conseiller·e"),
                    ("OBSERVER", "Observateur·trice"),
                ],
                default="COLLABORATOR",
                max_length=20,
            ),
        ),
    ]
