# Generated by Django 4.2.19 on 2025-03-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0109_alter_project_inactive_reason_and_more"),
        ("invites", "0003_alter_invite_role_squashed_0005_alter_invite_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invites",
                to="projects.project",
                verbose_name="dossier",
            ),
        ),
    ]
