# Generated by Django 5.1.11 on 2025-08-25 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invites", "0006_alter_invite_project"),
        ("projects", "0111_delete_perm_use_project_tags"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="refused_on",
            field=models.DateTimeField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                verbose_name="date de refus",
            ),
        ),
        migrations.AddConstraint(
            model_name="invite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("accepted_on", None), ("refused_on", None)),
                    models.Q(
                        ("accepted_on", None),
                        models.Q(("refused_on", None), _negated=True),
                    ),
                    models.Q(
                        models.Q(("accepted_on", None), _negated=True),
                        ("refused_on", None),
                    ),
                    _connector="OR",
                ),
                name="invites_invite_accepted_or_refused",
            ),
        ),
    ]
