# Generated by Django 5.1.14 on 2025-12-03 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("tasks", "0002_alter_task_created_on"),
        ("tasks", "0003_alter_task_options"),
    ]

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="date et heure de création",
            ),
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ("order",),
                "verbose_name": "action",
                "verbose_name_plural": "actions",
            },
        ),
    ]
