# Generated by Django 4.2.10 on 2024-03-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_created_on"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ("order",),
                "verbose_name": "action",
                "verbose_name_plural": "actions",
            },
        ),
    ]
