# Generated by Django 4.2.13 on 2024-07-02 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0096_alter_note_site"),
        ("tasks", "0002_alter_task_created_on_squashed_0003_alter_task_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="projects.topic",
            ),
        ),
    ]
