# Generated by Django 4.2.11 on 2025-01-22 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("addressbook", "0010_organizationgroup_organization_group"),
        ("tasks", "0004_alter_task_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskfollowup",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="addressbook_contact",
                to="addressbook.contact",
            ),
        ),
    ]
