# Generated by Django 4.2.16 on 2025-02-04 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0031_resource_imported_from"),
        ("tasks", "0004_alter_task_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommandations",
                to="resources.resource",
            ),
        ),
    ]
