# Generated by Django 4.2.16 on 2025-02-04 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("addressbook", "0011_contact_created_contact_modified_and_more"),
        ("tasks", "0005_alter_task_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskfollowup",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_followups",
                to="addressbook.contact",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="addressbook.contact",
            ),
        ),
    ]
