# Generated by Django 5.1.14 on 2025-12-03 16:30

import taggit.managers
from django.db import migrations

from recoco.apps.tasks.models import TaskRecommendation


def tagging_to_taggit(model, tagging_field_name, taggit_field_name):
    for tr in model.objects.all():
        getattr(tr, taggit_field_name).add(
            *(tagging_tag.name for tagging_tag in getattr(tr, tagging_field_name).all())
        )


def up(apps, schema_editor):
    tagging_to_taggit(TaskRecommendation, "condition_tags", "condition_tags_taggit")


def down(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("tasks", "0006_taskfollowup_contact_alter_task_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskrecommendation",
            name="condition_tags_taggit",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.RunPython(up, down),
    ]
