# Generated by Django 5.1.15 on 2026-01-05 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0007_taskrecommendation_condition_tags_taggit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskrecommendation",
            old_name="condition_tags_taggit",
            new_name="condition_tags",
        ),
    ]
