# Generated by Django 5.1.15 on 2026-01-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0007_taskrecommendation_condition_tags_taggit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.TextField(blank=True, default="", verbose_name="Contenu"),
        ),
    ]
