# Generated by Django 3.2.5 on 2021-07-12 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "région",
                "verbose_name_plural": "régions",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geomatics.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "département",
                "verbose_name_plural": "départements",
            },
        ),
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insee", models.CharField(max_length=5)),
                ("postal", models.CharField(max_length=5)),
                ("name", models.CharField(max_length=64)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geomatics.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "commune",
                "verbose_name_plural": "communes",
            },
        ),
    ]
