# Generated by Django 3.2.5 on 2021-07-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geomatics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="commune",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
    ]
