# Generated by Django 4.2.17 on 2025-01-24 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hitcount", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hit",
            name="hitcount",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hits",
                to="hitcount.hitcount",
            ),
        ),
        migrations.AlterField(
            model_name="hit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="hit",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
