# Generated by Django 4.2.16 on 2024-11-25 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feature_flag", "0001_initial"),
        (
            "home",
            "0016_remove_unused_groups",
        ),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS waffle_flag CASCADE"),
        migrations.RunSQL("DROP TABLE IF EXISTS waffle_sample"),
        migrations.RunSQL("DROP TABLE IF EXISTS waffle_switch"),
        migrations.RunSQL("DROP TABLE IF EXISTS waffle_flag_groups"),
        migrations.RunSQL("DROP TABLE IF EXISTS waffle_flag_users"),
    ]
