# Generated by Django 4.2.12 on 2024-05-28 13:03

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0093_uploadedfile"),
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowcasePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "heading",
                    wagtail.fields.StreamField(
                        [
                            (
                                "hero",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "bg_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image d’arrière plan"
                                            ),
                                        ),
                                        (
                                            "bg_color",
                                            wagtail.blocks.RegexBlock(
                                                error_messages={
                                                    "invalid": "La couleur n’est pas correcte, le format doit être #fff ou #f5f5fe"
                                                },
                                                label="Couleur d’arrière plan au format hexa (Ex: #f5f5fe)",
                                                regex="^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(label="Titre"),
                                        ),
                                        (
                                            "text",
                                            wagtail.blocks.CharBlock(
                                                label="Texte", required=False
                                            ),
                                        ),
                                        (
                                            "cta_label",
                                            wagtail.blocks.CharBlock(
                                                label="Texte du bouton", required=False
                                            ),
                                        ),
                                        (
                                            "cta_link",
                                            wagtail.blocks.URLBlock(
                                                label="Lien du bouton", required=False
                                            ),
                                        ),
                                        (
                                            "darken",
                                            wagtail.blocks.BooleanBlock(
                                                label="Assombrir", required=False
                                            ),
                                        ),
                                    ],
                                    label="Hero",
                                ),
                            )
                        ],
                        verbose_name="En-tête",
                    ),
                ),
                (
                    "gallery",
                    wagtail.fields.StreamField(
                        [("pictures", wagtail.images.blocks.ImageChooserBlock())],
                        verbose_name="Gallerie",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "multicol",
                                wagtail.blocks.StreamBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(label="Titre"),
                                        ),
                                        (
                                            "columns",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "text",
                                                        wagtail.blocks.RichTextBlock(
                                                            label="Texte avec mise en forme"
                                                        ),
                                                    )
                                                ],
                                                label="Colonne",
                                            ),
                                        ),
                                    ],
                                    label="Multi Colonnes",
                                ),
                            ),
                            (
                                "richtext",
                                wagtail.blocks.RichTextBlock(label="Texte riche"),
                            ),
                        ],
                        verbose_name="Contenu",
                    ),
                ),
                (
                    "quote",
                    wagtail.fields.StreamField(
                        [
                            (
                                "quote",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Illustration (à gauche)",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "quote",
                                            wagtail.blocks.TextBlock(label="Citation"),
                                        ),
                                        (
                                            "author_name",
                                            wagtail.blocks.CharBlock(
                                                label="Nom de l’auteur"
                                            ),
                                        ),
                                        (
                                            "author_title",
                                            wagtail.blocks.CharBlock(
                                                label="Titre de l’auteur"
                                            ),
                                        ),
                                    ],
                                    label="Citation",
                                ),
                            )
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
