# Generated by Django 4.2.13 on 2024-06-24 08:57

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_showcasepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showcasepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "multicol",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        label="Titre", required=False
                                    ),
                                ),
                                (
                                    "columns",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.RichTextBlock(
                                                    label="Texte avec mise en forme"
                                                ),
                                            )
                                        ],
                                        label="Colonne",
                                    ),
                                ),
                            ],
                            label="Multi Colonnes",
                        ),
                    ),
                    ("richtext", wagtail.blocks.RichTextBlock(label="Texte riche")),
                ],
                verbose_name="Contenu",
            ),
        ),
        migrations.AlterField(
            model_name="showcasepage",
            name="gallery",
            field=wagtail.fields.StreamField(
                [("pictures", wagtail.images.blocks.ImageChooserBlock())],
                blank=True,
                verbose_name="Gallerie",
            ),
        ),
        migrations.AlterField(
            model_name="showcasepage",
            name="heading",
            field=wagtail.fields.StreamField(
                [
                    (
                        "hero",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "bg_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Image d’arrière plan", required=False
                                    ),
                                ),
                                (
                                    "bg_color",
                                    wagtail.blocks.RegexBlock(
                                        error_messages={
                                            "invalid": "La couleur n’est pas correcte, le format doit être #fff ou #f5f5fe"
                                        },
                                        label="Couleur d’arrière plan au format hexa (Ex: #f5f5fe)",
                                        regex="^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$",
                                        required=False,
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(label="Titre")),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        label="Texte", required=False
                                    ),
                                ),
                                (
                                    "cta_label",
                                    wagtail.blocks.CharBlock(
                                        label="Texte du bouton", required=False
                                    ),
                                ),
                                (
                                    "cta_link",
                                    wagtail.blocks.URLBlock(
                                        label="Lien du bouton", required=False
                                    ),
                                ),
                                (
                                    "darken",
                                    wagtail.blocks.BooleanBlock(
                                        label="Assombrir", required=False
                                    ),
                                ),
                            ],
                            label="Hero",
                        ),
                    )
                ],
                verbose_name="En-tête",
            ),
        ),
        migrations.AlterField(
            model_name="showcasepage",
            name="quote",
            field=wagtail.fields.StreamField(
                [
                    (
                        "quote",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Illustration (à gauche)", required=False
                                    ),
                                ),
                                ("quote", wagtail.blocks.TextBlock(label="Citation")),
                                (
                                    "author_name",
                                    wagtail.blocks.CharBlock(label="Nom de l’auteur"),
                                ),
                                (
                                    "author_title",
                                    wagtail.blocks.CharBlock(label="Titre de l’auteur"),
                                ),
                            ],
                            label="Citation",
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
