# Generated by Django 4.2.13 on 2024-09-24 12:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0093_uploadedfile"),
        ("pages", "0003_alter_showcasepage_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatisticsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "multicol",
                                wagtail.blocks.StreamBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                label="Titre", required=False
                                            ),
                                        ),
                                        (
                                            "columns",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "text",
                                                        wagtail.blocks.RichTextBlock(
                                                            label="Texte avec mise en forme"
                                                        ),
                                                    )
                                                ],
                                                label="Colonne",
                                            ),
                                        ),
                                    ],
                                    label="Multi Colonnes",
                                ),
                            ),
                            (
                                "richtext",
                                wagtail.blocks.RichTextBlock(label="Texte riche"),
                            ),
                        ],
                        blank=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
