# Generated by Django 5.1.13 on 2025-11-03 14:14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_showcaselistpage"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NewsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "heading",
                    wagtail.fields.StreamField(
                        [("hero", 7)],
                        block_lookup={
                            0: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image d’arrière plan", "required": False},
                            ),
                            1: (
                                "wagtail.blocks.RegexBlock",
                                (),
                                {
                                    "error_messages": {
                                        "invalid": "La couleur n’est pas correcte, le format doit être #fff ou #f5f5fe"
                                    },
                                    "label": "Couleur d’arrière plan au format hexa (Ex: #f5f5fe)",
                                    "regex": "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$",
                                    "required": False,
                                },
                            ),
                            2: ("wagtail.blocks.CharBlock", (), {"label": "Titre"}),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Texte", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Texte du bouton", "required": False},
                            ),
                            5: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "Lien du bouton", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"label": "Assombrir", "required": False},
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("bg_image", 0),
                                        ("bg_color", 1),
                                        ("title", 2),
                                        ("text", 3),
                                        ("cta_label", 4),
                                        ("cta_link", 5),
                                        ("darken", 6),
                                    ]
                                ],
                                {"label": "Hero"},
                            ),
                        },
                        verbose_name="En-tête",
                    ),
                ),
                (
                    "gallery",
                    wagtail.fields.StreamField(
                        [("pictures", 0)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.images.blocks.ImageChooserBlock", (), {})
                        },
                        verbose_name="Gallerie",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("multicol", 3), ("richtext", 4)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Titre", "required": False},
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"label": "Texte avec mise en forme"},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 1)]],
                                {"label": "Colonne"},
                            ),
                            3: (
                                "wagtail.blocks.StreamBlock",
                                [[("title", 0), ("columns", 2)]],
                                {"label": "Multi Colonnes"},
                            ),
                            4: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"label": "Texte riche"},
                            ),
                        },
                        verbose_name="Contenu",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
