# Generated by Django 3.2.4 on 2021-06-16 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public", models.BooleanField(blank=True, default=False)),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date de création",
                    ),
                ),
                ("tags", models.CharField(blank=True, default="", max_length=256)),
                ("title", models.CharField(max_length=128)),
                ("content", models.TextField()),
                ("deleted", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ressource",
                "verbose_name_plural": "ressources",
            },
        ),
    ]
