# Generated by Django 3.2.3 on 2021-06-21 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_auto_20210621_1701"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="updated_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="dernière modification"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="created_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date de création"
            ),
        ),
    ]
