# Generated by Django 3.2.3 on 2021-06-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0004_auto_20210621_1708"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                choices=[
                    ("blue", "Bleu"),
                    ("black", "Black"),
                    ("yellow", "Jaune"),
                    ("orange", "Orange"),
                    ("red", "Rouge"),
                    ("green", "Vert"),
                    ("violet", "Violet"),
                ],
                max_length=16,
            ),
        ),
    ]
