# Generated by Django 3.2.4 on 2021-06-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0007_auto_20210622_1138"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resource",
            old_name="quote",
            new_name="summary",
        ),
    ]
