# Generated by Django 3.2.4 on 2021-06-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0008_bookmark"),
        ("resources", "0008_rename_quote_resource_summary"),
    ]

    operations = []
