# Generated by Django 3.2.4 on 2021-06-29 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_project_phone"),
        ("resources", "0009_merge_20210628_1911"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="projects.project",
            ),
        ),
    ]
