# Generated by Django 3.2.4 on 2021-07-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0011_alter_bookmark_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmark",
            name="project",
        ),
    ]
