# Generated by Django 3.2.3 on 2021-07-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geomatics", "0001_initial"),
        ("resources", "0012_remove_bookmark_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="geomatics.Department",
                verbose_name="Départements concernés",
            ),
        ),
    ]
