# Generated by Django 3.2.5 on 2021-07-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geomatics", "0002_auto_20210713_0921"),
        ("resources", "0013_resource_departments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                to="geomatics.Department",
                verbose_name="Départements concernés",
            ),
        ),
    ]
