# Generated by Django 3.2.3 on 2021-10-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0016_auto_20210809_1230"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="expires_on",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="date d'expiration"
            ),
        ),
    ]
