# Generated by Django 3.2.3 on 2021-10-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0017_resource_expires_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="expires_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="date d'expiration"
            ),
        ),
    ]
