# Generated by Django 3.2.3 on 2022-02-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0020_resource_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="public",
        ),
    ]
