# Generated by Django 3.2.13 on 2022-05-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("resources", "0021_remove_resource_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="sites",
            field=models.ManyToManyField(to="sites.Site"),
        ),
    ]
