# Generated by Django 3.2.13 on 2022-05-04 07:41

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("resources", "0022_resource_sites"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="category",
            managers=[
                ("on_site", django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="resource",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="sites",
            field=models.ManyToManyField(to="sites.Site"),
        ),
    ]
