# Generated by Django 3.2.15 on 2022-10-11 09:15

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("resources", "0026_rename_tags_resource_old_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
