# Generated by Django 3.2.15 on 2022-10-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0028_migrate_tagging"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="old_tags",
        ),
    ]
