# Generated by Django 3.2.3 on 2021-06-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="contact",
            new_name="last_name",
        ),
        migrations.AddField(
            model_name="project",
            name="first_name",
            field=models.CharField(
                default="", max_length=128, verbose_name="Prénom du contact"
            ),
        ),
    ]
