# Generated by Django 3.2.3 on 2021-06-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210601_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='org_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Nom de votre structure'),
        ),
    ]
