# Generated by Django 3.2.3 on 2021-06-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_org_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='org_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Nom de votre structure'),
        ),
    ]
