# Generated by Django 3.2.4 on 2021-06-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_project_org_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Resource",
        ),
    ]
