# Generated by Django 3.2.4 on 2021-06-16 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_delete_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="updated_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="updated_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Dernière mise à jour"
            ),
        ),
    ]
