# Generated by Django 3.2.4 on 2021-06-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_auto_20210616_1824"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=16, verbose_name="Téléphone"
            ),
        ),
    ]
