# Generated by Django 3.2.4 on 2021-07-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_project_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_draft",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="projects.project",
            ),
        ),
    ]
