# Generated by Django 3.2.4 on 2021-07-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_auto_20210706_1301"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="intent",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
