# Generated by Django 3.2.3 on 2021-07-12 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geomatics", "0001_initial"),
        ("projects", "0010_task_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="commune",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geomatics.commune",
                verbose_name="Commune",
            ),
        ),
    ]
