# Generated by Django 3.2.3 on 2021-09-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_alter_note_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
