# Generated by Django 3.2.3 on 2021-09-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_alter_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="accepted",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
