# Generated by Django 3.2.3 on 2021-09-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_task_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="refused",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
