# Generated by Django 3.2.3 on 2021-09-27 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_task_refused"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ro_key",
            field=models.CharField(
                default=uuid.uuid4().hex,
                editable=False,
                max_length=32,
                verbose_name="Clé d'accès lecture seule",
            ),
            preserve_default=False,
        ),
    ]
