# Generated by Django 3.2.3 on 2021-10-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_alter_project_ro_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="accepted",
            new_name="visited",
        ),
    ]
