# Generated by Django 3.2.3 on 2021-10-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_taskfollowuprsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='exclude_stats',
            field=models.BooleanField(default=False),
        ),
    ]
