# Generated by Django 3.2.3 on 2021-10-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geomatics", "0003_alter_department_code"),
        ("projects", "0030_taskrecommandation"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskrecommandation",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                to="geomatics.Department",
                verbose_name="Départements concernés",
            ),
        ),
    ]
