# Generated by Django 3.2.3 on 2021-10-27 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0016_auto_20210809_1230"),
        ("geomatics", "0003_alter_department_code"),
        ("projects", "0031_taskrecommandation_departments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TaskRecommandation",
            new_name="TaskRecommendation",
        ),
    ]
