# Generated by Django 3.2.3 on 2021-11-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_rename_taskrecommandation_taskrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='publish_to_cartofriches',
            field=models.BooleanField(default=False, verbose_name='Publier sur cartofriches'),
        ),
    ]
