# Generated by Django 3.2.9 on 2021-11-15 13:49

from django.db import migrations


# def create_switchtender_group(apps, schema_editor):
#     """Create the switchtender group for their permissions"""
#     db_alias = schema_editor.connection.alias
#     Group = apps.get_model("auth", "Group")
#     g, _ = Group.objects.using(db_alias).get_or_create(name="example_com_advisor")
#     Permission = apps.get_model("auth", "Permission")
#     p = Permission.objects.get(codename="can_administrate_project")
#     g.permissions.add(p)
#
#
# def delete_switchtender_group(apps, schema_editor):
#     """Delete the switchtender group"""
#     db_alias = schema_editor.connection.alias
#     Group = apps.get_model("auth", "Group")
#     Group.objects.using(db_alias).filter(name="example_com_advisor").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0033_project_publish_to_cartofriches"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "permissions": (
                    (
                        "can_administrate_project",
                        "Aiguilleuse > Peut administrer un projet",
                    ),
                ),
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
    ]
