# Generated by Django 3.2.3 on 2021-12-07 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0019_resource_created_by"),
        ("projects", "0037_taskfollowuprsvp_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskrecommendation",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_recommendations",
                to="resources.resource",
            ),
        ),
    ]
