# Generated by Django 3.2.3 on 2021-12-07 11:04

from django.db import migrations, models


def set_status(apps, schema_editor):
    Project = apps.get_model("projects", "Project")

    for project in Project.objects.all().iterator():
        project.status = "DRAFT" if project.is_draft else "READY"
        project.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0038_alter_taskrecommendation_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("TO_PROCESS", "A traiter"),
                    ("QUESTIONS", "En attente de retour de la collectivité"),
                    ("READY", "Prêt à aiguiller"),
                    ("IN_PROGRESS", "Recommandations en cours"),
                    ("REVIEW_REQUEST", "Demande de relecture"),
                    ("DONE", "Appui réalisé"),
                    ("STUCK", "En attente/bloqué"),
                    ("REJECTED", "Rejeté"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_status, reverse_func),
    ]
