# Generated by Django 3.2.3 on 2021-12-07 11:19

from django.db import migrations


def noop_func(apps, schema_editor):
    pass


def set_is_draft_field(apps, schema_editor):
    Project = apps.get_model("projects", "Project")

    for project in Project.objects.all().iterator():
        project.is_draft = project.status == "DRAFT"
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0039_project_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="is_draft",
        ),
        migrations.RunPython(noop_func, set_is_draft_field),
    ]
