# Generated by Django 3.2.3 on 2022-01-18 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0041_note_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="switchtender",
        ),
        migrations.AddField(
            model_name="project",
            name="switchtenders",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects_managed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aiguilleu·r·se",
            ),
        ),
    ]
