# Generated by Django 3.2.3 on 2022-01-31 16:19

from django.db import migrations, transaction

from ..models import Task


def compute_status(apps, schema_editor):
    """Compute status based existing fields"""
    TaskModel = apps.get_model("projects", "Task")

    with transaction.atomic():
        for task in TaskModel.objects.all():
            if task.done:
                task.status = Task.DONE
            elif task.refused:
                task.status = Task.NOT_INTERESTED

            task.save()


def reverse_status(apps, schema_editor):
    """Fill fields based on status"""
    TaskModel = apps.get_model("projects", "Task")

    with transaction.atomic():
        for task in TaskModel.objects.all():
            if task.status == Task.DONE:
                task.done = True
            elif task.status == Task.NOT_INTERESTED or task.status == Task.ALREADY_DONE:
                task.refused = True

            task.save()


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0043_auto_20220131_1710"),
    ]

    operations = [
        migrations.RunPython(compute_status, reverse_status),
    ]
