# Generated by Django 3.2.3 on 2022-02-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0044_auto_20220131_1719"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "proposé"),
                    (1, "en cours"),
                    (2, "blocage"),
                    (3, "terminé"),
                    (4, "pas intéressé·e"),
                    (5, "déjà fait"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="taskfollowup",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "proposé"),
                    (1, "en cours"),
                    (2, "blocage"),
                    (3, "terminé"),
                    (4, "pas intéressé·e"),
                    (5, "déjà fait"),
                ]
            ),
        ),
    ]
