# Generated by Django 3.2.3 on 2022-02-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0045_auto_20220202_1635"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="muted",
            field=models.BooleanField(
                default=False, verbose_name="Ne pas envoyer de notifications"
            ),
        ),
    ]
