# Generated by Django 3.2.3 on 2022-04-27 13:29

from django.db import migrations, models


def noop_func(apps, schema_editor):
    pass


def set_order_from_priority(apps, schema_editor):
    Project = apps.get_model("projects", "Project")

    for project in Project.objects.all().iterator():
        for idx, t in enumerate(project.tasks.order_by("-priority").all()):
            t.order = idx + 1
            t.save()


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0047_alter_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_order_from_priority, noop_func),
    ]
