# Generated by Django 3.2.13 on 2022-05-04 13:38

from django.db import migrations, models
import django.db.models.manager
import urbanvitaliz.apps.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("projects", "0048_task_order"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="project",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", urbanvitaliz.apps.projects.models.ProjectOnSiteManager()),
                (
                    "deleted_on_site",
                    urbanvitaliz.apps.projects.models.DeletedProjectOnSiteManager(),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="sites",
            field=models.ManyToManyField(to="sites.Site"),
        ),
    ]
