# Generated by Django 3.2.13 on 2022-05-05 16:47

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import urbanvitaliz.apps.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("projects", "0049_auto_20220504_1538"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="task",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", urbanvitaliz.apps.projects.models.TaskOnSiteManager()),
                (
                    "deleted_on_site",
                    urbanvitaliz.apps.projects.models.DeletedTaskOnSiteManager(),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
            preserve_default=False,
        ),
    ]
