# Generated by Django 3.2.13 on 2022-05-31 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0049_alter_taskfollowup_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="public",
        ),
        migrations.RemoveField(
            model_name="document",
            name="tags",
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="projects.project",
            ),
        ),
    ]
