# Generated by Django 3.2.13 on 2022-05-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0050_auto_20220524_1109"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="email",
        ),
        migrations.RemoveField(
            model_name="project",
            name="emails",
        ),
    ]
