# Generated by Django 3.2.13 on 2022-05-06 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import urbanvitaliz.apps.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("projects", "0050_auto_20220505_1847"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="taskrecommendation",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                (
                    "on_site",
                    urbanvitaliz.apps.projects.models.TaskRecommendationOnSiteManager(),
                ),
            ],
        ),
        migrations.AddField(
            model_name="taskrecommendation",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
            preserve_default=False,
        ),
    ]
