# Generated by Django 3.2.13 on 2022-06-01 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0051_alter_document_the_file"),
        ("projects", "0051_auto_20220524_1129"),
    ]

    operations = []
