# Generated by Django 3.2.13 on 2022-05-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0049_alter_taskfollowup_status"),
        ("projects", "0051_auto_20220506_1146"),
    ]

    operations = []
