# Generated by Django 3.2.13 on 2022-06-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0052_merge_20220523_1203"),
        ("projects", "0052_merge_20220601_1012"),
    ]

    operations = []
