# Generated by Django 3.2.13 on 2022-07-05 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sites", "0002_alter_domain_unique"),
        ("projects", "0053_merge_20220601_1401"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSwitchtender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
                (
                    "example_com_advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("site", "project", "example_com_advisor")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="project_switchtenders",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects_switchtended",
                through="projects.ProjectSwitchtender",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aiguilleu·r·se·s",
            ),
        ),
    ]
