# Generated by Django 3.2.13 on 2022-07-05 11:36

from django.db import migrations


def copy_switchtenders_to_m2m(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    ProjectSwitchtender = apps.get_model("projects", "ProjectSwitchtender")
    db_alias = schema_editor.connection.alias

    for project in Project.objects.using(db_alias).all():
        for switchtender in project.switchtenders.all():
            ProjectSwitchtender.objects.using(db_alias).create(
                switchtender=switchtender, project=project, site_id=1
            )


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0054_auto_20220705_1335"),
    ]

    operations = [
        migrations.RunPython(copy_switchtenders_to_m2m, lambda x, y: None),
    ]
