# Generated by Django 3.2.13 on 2022-07-05 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0055_auto_20220705_1336"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="switchtenders",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="project_switchtenders",
            new_name="switchtenders",
        ),
    ]
