# Generated by Django 3.2.14 on 2022-08-01 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import urbanvitaliz.apps.projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0056_auto_20220705_1342"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="projectswitchtender",
            managers=[
                (
                    "objects",
                    urbanvitaliz.apps.projects.models.ProjectSwitchtenderOnSiteManager(),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="projectswitchtender",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="switchtenders_on_site",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="projectswitchtender",
            name="example_com_advisor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects_switchtended_on_site",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
