# Generated by Django 3.2.14 on 2022-08-23 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0057_auto_20220801_1717"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="synopsis",
            field=models.TextField(
                blank=True,
                default="",
                null=True,
                verbose_name="Reformulation du besoin",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="synopsis_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="synopses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reformulé par",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="synopsis_on",
            field=models.DateTimeField(null=True, verbose_name="Reformulé le"),
        ),
    ]
