# Generated by Django 3.2.15 on 2022-09-05 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0058_auto_20220823_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='synopsis_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synopses', to=settings.AUTH_USER_MODEL, verbose_name='Reformulé par'),
        ),
        migrations.AlterField(
            model_name='project',
            name='synopsis_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reformulé le'),
        ),
    ]
