# Generated by Django 3.2.15 on 2022-09-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_auto_20220905_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': [], 'permissions': [('add_private_note', 'Can add a private note'), ('change_private_note', 'Can change a private note'), ('delete_private_note', 'Can delete a private note'), ('view_private_note', 'Can view a private note'), ('add_public_note', 'Can add a public note'), ('change_public_note', 'Can change a public note'), ('delete_public_note', 'Can delete a public note'), ('view_public_note', 'Can view a public note')], 'verbose_name': 'note', 'verbose_name_plural': 'notes'},
        ),
    ]
