# Generated by Django 3.2.15 on 2022-09-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('use_private_notes', 'Can use the private notes'), ('use_public_notes', 'Can use the public notes'), ('view_tasks', 'Can view and list tasks'), ('use_tasks', 'Can use tasks'), ('manage_tasks', 'Can manage tasks')), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
    ]
