# Generated by Django 3.2.16 on 2022-10-24 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import urbanvitaliz.apps.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0062_projectswitchtender_is_observer"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProjectStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FOLLOWED", "Suivi"),
                            ("NOT_INTERESTED", "Pas d'intérêt"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_project_states",
                        to="projects.project",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("site", "user", "project")},
            },
            managers=[
                (
                    "objects",
                    urbanvitaliz.apps.projects.models.UserProjectStatusOnSiteManager(),
                ),
            ],
        ),
    ]
