# Generated by Django 3.2.16 on 2022-10-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0063_userprojectstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprojectstatus",
            name="status",
            field=models.CharField(
                choices=[("FOLLOWED", "Suivi"), ("NOT_INTERESTED", "Pas d'intérêt")],
                max_length=20,
            ),
        ),
    ]
