# Generated by Django 3.2.15 on 2022-10-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_alter_project_tags'),
        ('projects', '0063_alter_project_options'),
    ]

    operations = [
    ]
