# Generated by Django 3.2.16 on 2022-10-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_alter_userprojectstatus_status'),
        ('projects', '0064_merge_20221018_1426'),
    ]

    operations = [
    ]
