# Generated by Django 3.2.16 on 2022-11-16 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0064_alter_userprojectstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Déposé par'),
        ),
    ]
