# Generated by Django 3.2.16 on 2022-11-16 17:46

from django.db import migrations, models, transaction


def reduce_statuses(apps, schema_editor):
    """Compute new statuses based existing"""
    Project = apps.get_model("projects", "Project")

    with transaction.atomic():
        Project.objects.filter(status="QUESTIONS").update(status="READY")
        Project.objects.filter(status="REVIEW_REQUEST").update(status="DONE")


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0065_project_submitted_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("TO_PROCESS", "A traiter"),
                    ("READY", "En attente"),
                    ("IN_PROGRESS", "En cours"),
                    ("DONE", "Traité"),
                    ("STUCK", "Conseil Interrompu"),
                    ("REJECTED", "Rejeté"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.RunPython(reduce_statuses, lambda x, y: None),
    ]
