# Generated by Django 3.2.16 on 2022-11-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_auto_20221128_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
