# Generated by Django 3.2.16 on 2022-11-28 15:06

from django.db import migrations, models
import urbanvitaliz.apps.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_document_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='the_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='the_file',
            field=models.FileField(blank=True, null=True, upload_to=urbanvitaliz.apps.projects.models.Document.upload_path),
        ),
    ]
