# Generated by Django 3.2.16 on 2022-11-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_auto_20221128_1639'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='not_both_link_and_file_are_null',
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('the_file__isnull', False), ('the_link', None)), models.Q(('the_file', None), ('the_link__isnull', False)), _connector='OR'), name='not_both_link_and_file_are_null'),
        ),
    ]
