# Generated by Django 3.2.16 on 2022-12-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0072_auto_20221128_1640'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='not_both_link_and_file_are_null',
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('the_file__exact', ''), ('the_link__isnull', True)), _negated=True), name='not_both_link_and_file_are_null'),
        ),
    ]
