# Generated by Django 3.2.16 on 2022-12-19 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0074_auto_20221219_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='advisors_note',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Note interne'),
        ),
        migrations.AlterField(
            model_name='project',
            name='advisors_note_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisors_notes', to=settings.AUTH_USER_MODEL, verbose_name='Rédigé par'),
        ),
        migrations.AlterField(
            model_name='project',
            name='advisors_note_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rédigé le'),
        ),
    ]
