# Generated by Django 3.2.16 on 2023-01-16 13:35

from django.db import migrations, models


def split_statuses(apps, schema_editor):
    UserProjectStatus = apps.get_model("projects", "UserProjectStatus")

    UserProjectStatus.objects.filter(status="FOLLOWED").update(status="TODO")


def merge_statuses(apps, schema_editor):
    UserProjectStatus = apps.get_model("projects", "UserProjectStatus")

    UserProjectStatus.objects.exclude(status="NOT_INPROGRESS").update(status="FOLLOWED")


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0075_auto_20221219_1509"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprojectstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("TODO", "A traiter"),
                    ("WIP", "En cours"),
                    ("DONE", "Traité"),
                    ("NOT_INTERESTED", "Pas d'intérêt"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(split_statuses, merge_statuses),
    ]
