# Generated by Django 3.2.16 on 2023-02-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0078_merge_20230213_1432"),
    ]

    operations = []
