# Generated by Django 3.2.16 on 2023-03-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0083_update_to_project_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "permissions": (
                    ("change_topics", "Can change the topics"),
                    ("use_advisor_note", "Can change the advisor note"),
                    ("use_private_notes", "Can use the private notes (internal)"),
                    ("use_public_notes", "Can use the public notes (conversations)"),
                    ("view_public_notes", "Can read the public notes (conversations)"),
                    ("view_private_notes", "Can read the private notes (internal)"),
                    ("view_surveys", "Can view the survey results"),
                    ("use_surveys", "Can use the surveys"),
                    ("view_tasks", "Can view and list tasks"),
                    ("view_draft_tasks", "Can view and list draft tasks"),
                    ("use_tasks", "Can use tasks"),
                    ("manage_tasks", "Can manage tasks"),
                    ("manage_documents", "Can manage the documents"),
                    ("invite_collaborators", "Can invite collaborators"),
                    ("invite_advisors", "Can invite advisors"),
                    ("manage_collaborators", "Can manage collaborators"),
                    ("manage_advisors", "Can manage advisors"),
                ),
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
    ]
