# Generated by Django 3.2.16 on 2023-04-07 13:57

from django.db import migrations, models
import django.db.models.deletion
import urbanvitaliz.apps.projects.models

from urbanvitaliz.apps.projects.models import Note


def assign_note_site_based_on_project_site(apps, schema_editor):
    for note in Note.objects.all():
        project_site = note.project.sites.first()
        if project_site:
            note.site = project_site
            note.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("projects", "0084_alter_project_options"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="note",
            managers=[
                ("on_site", urbanvitaliz.apps.projects.models.NoteOnSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name="note",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ptroject_notes",
                to="sites.site",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(assign_note_site_based_on_project_site, lambda x, y: None),
    ]
