# Generated by Django 3.2.16 on 2023-04-07 14:23

from django.db import migrations
import django.db.models.manager
import urbanvitaliz.apps.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0085_add_on_site_to_notes'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='note',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', urbanvitaliz.apps.projects.models.NoteOnSiteManager()),
            ],
        ),
    ]
