# Generated by Django 3.2.18 on 2023-05-22 09:37

from django.db import migrations, models
import django.db.models.manager
import urbanvitaliz.apps.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0088_alter_project_options"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="project",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                (
                    "on_site",
                    urbanvitaliz.apps.projects.models.ActiveProjectOnSiteManager(),
                ),
                (
                    "deleted_on_site",
                    urbanvitaliz.apps.projects.models.DeletedProjectOnSiteManager(),
                ),
                (
                    "all_on_site",
                    urbanvitaliz.apps.projects.models.ProjectOnSiteManager(),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="project",
            name="exclude_stats",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="muted",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name="Ne pas envoyer de notifications",
            ),
        ),
    ]
