# Generated by Django 3.2.18 on 2023-08-29 12:13

from django.db import migrations, models
import django.db.models.deletion
import urbanvitaliz.apps.projects.models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("projects", "0089_auto_20230522_1137"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "site")},
            },
            managers=[
                ("objects", urbanvitaliz.apps.projects.models.TopicOnSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="projects.Topic"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="projects.topic",
            ),
        ),
    ]
