# Generated by Django 3.2.18 on 2023-09-05 14:03
# update by hand to manage migration of table to app tasks

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0090_topic_for_projects_and_tasks"),
    ]

    operations = [
        # update models as unmanaged, so that underlying tables are kept
        migrations.AlterModelOptions(
            name="Task",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="TaskFollowup",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="TaskFollowupRsvp",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="TaskRecommendation",
            options={"managed": False},
        ),
        # remove existing relations (generated)
        migrations.RemoveField(
            model_name="taskfollowup",
            name="task",
        ),
        migrations.RemoveField(
            model_name="taskfollowup",
            name="who",
        ),
        migrations.RemoveField(
            model_name="taskfollowuprsvp",
            name="task",
        ),
        migrations.RemoveField(
            model_name="taskfollowuprsvp",
            name="user",
        ),
        migrations.RemoveField(
            model_name="taskrecommendation",
            name="departments",
        ),
        migrations.RemoveField(
            model_name="taskrecommendation",
            name="resource",
        ),
        migrations.RemoveField(
            model_name="taskrecommendation",
            name="site",
        ),
        # remove models but not tables as unmanaged (generated)
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="TaskFollowup",
        ),
        migrations.DeleteModel(
            name="TaskFollowupRsvp",
        ),
        migrations.DeleteModel(
            name="TaskRecommendation",
        ),
    ]
