# Generated by Django 3.2.18 on 2023-09-05 14:03
# update by hand to manage migration of table to app tasks

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0090_topic_for_projects_and_tasks"),
        # First create new table in tasks application and rename tables
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="taskfollowup",
                    name="task",
                ),
                migrations.RemoveField(
                    model_name="taskfollowup",
                    name="who",
                ),
                migrations.RemoveField(
                    model_name="taskfollowuprsvp",
                    name="task",
                ),
                migrations.RemoveField(
                    model_name="taskfollowuprsvp",
                    name="user",
                ),
                migrations.RemoveField(
                    model_name="taskrecommendation",
                    name="departments",
                ),
                migrations.RemoveField(
                    model_name="taskrecommendation",
                    name="resource",
                ),
                migrations.RemoveField(
                    model_name="taskrecommendation",
                    name="site",
                ),
                migrations.DeleteModel(
                    name="Task",
                ),
                migrations.DeleteModel(
                    name="TaskFollowup",
                ),
                migrations.DeleteModel(
                    name="TaskFollowupRsvp",
                ),
                migrations.DeleteModel(
                    name="TaskRecommendation",
                ),
            ],
            # Do nothing as tables have already been renamed by task migration 0001
            database_operations=[],
        ),
    ]
