# Generated by Django 3.2.18 on 2023-10-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0091_moving_task_to_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="inactive_reason",
            field=models.CharField(
                blank=True,
                default="",
                max_length=256,
                null=True,
                verbose_name="Raison de l'inactivité du projet",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="inactive_since",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Quand le projet a été déclaré inactif",
            ),
        ),
    ]
