# Generated by Django 5.1.14 on 2025-12-03 10:35

import django.db.models.deletion
import recoco.apps.survey.models
import tagging.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("survey", "0001_initial"),
        ("survey", "0002_question_text"),
        ("survey", "0003_auto_20210727_1430"),
        ("survey", "0004_session_survey"),
        ("survey", "0005_auto_20210727_1716"),
        ("survey", "0006_survey_name"),
        ("survey", "0007_auto_20210803_1053"),
        ("survey", "0008_auto_20210803_1554"),
        ("survey", "0009_choice_signals"),
        ("survey", "0010_alter_choice_signals"),
        ("survey", "0011_alter_questionset_icon"),
        ("survey", "0012_question_precondition"),
        ("survey", "0013_answer_signals"),
        ("survey", "0014_question_priority"),
        ("survey", "0015_auto_20210817_1008"),
        ("survey", "0016_auto_20210817_1033"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Sans Nom", max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=255, verbose_name="En-tête")),
                ("subheading", models.TextField(verbose_name="Sous-titre")),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_sets",
                        to="survey.survey",
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=80, verbose_name="Icône"),
                ),
                ("deleted", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="survey.questionset",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        max_length=255, verbose_name="Texte de la question"
                    ),
                ),
                ("deleted", models.DateTimeField(null=True)),
                (
                    "precondition",
                    tagging.fields.TagField(
                        blank=True,
                        help_text="Affiche cette question si TOUS les signaux saisis sont émis",
                        max_length=255,
                        verbose_name="Pré-condition",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Priorité d'affichage. Le plus fort, le plus important.",
                        verbose_name="Priorité",
                    ),
                ),
                ("how", models.TextField(blank=True, default="")),
                ("why", models.TextField(blank=True, default="")),
                ("is_multiple", models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="survey.survey",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=30)),
                ("text", models.CharField(max_length=255)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="survey.question",
                    ),
                ),
                ("deleted", models.DateTimeField(null=True)),
                (
                    "signals",
                    tagging.fields.TagField(
                        blank=True, max_length=255, verbose_name="Signaux"
                    ),
                ),
            ],
            options={
                "unique_together": {("value", "question")},
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="survey.question",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="survey.session",
                    ),
                ),
                ("value", models.CharField(default="", max_length=30)),
                ("comment", models.TextField(blank=True)),
                (
                    "signals",
                    tagging.fields.TagField(
                        blank=True, max_length=255, null=True, verbose_name="Signaux"
                    ),
                ),
                (
                    "values",
                    models.JSONField(
                        blank=True, default=recoco.apps.survey.models.empty_answer
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "question")},
            },
        ),
    ]
