# Generated by Django 5.1.14 on 2025-12-03 10:36

import recoco.apps.survey.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0018_alter_session_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="how",
            field=models.TextField(blank=True, default="", verbose_name="Comment ?"),
        ),
        migrations.AlterField(
            model_name="question",
            name="is_multiple",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Est un QCM ?"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="why",
            field=models.TextField(blank=True, default="", verbose_name="Pourquoi ?"),
        ),
        migrations.AlterField(
            model_name="questionset",
            name="deleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="comment_title",
            field=models.CharField(
                blank=True,
                default="Commentaire",
                max_length=255,
                verbose_name="Titre du commentaire",
            ),
        ),
        migrations.AlterField(
            model_name="questionset",
            name="subheading",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Sous-titre"
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="priority",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Priorité d'affichage. Le plus fort, le plus important.",
                verbose_name="Priorité",
            ),
        ),
        migrations.AddField(
            model_name="questionset",
            name="color",
            field=models.CharField(
                blank=True, default="orange", max_length=10, verbose_name="Couleur"
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="conclusion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="upload_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Si rempli, il sera possible de téléverser un fichier",
                max_length=255,
                verbose_name="Titre du Téléversement",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=recoco.apps.survey.models.survey_private_file_path,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="text_short",
            field=models.CharField(
                default="", max_length=32, verbose_name="Texte court de la question"
            ),
        ),
        migrations.AddField(
            model_name="questionset",
            name="priority",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Priorité d'affichage. Le plus fort, le plus important.",
                verbose_name="Priorité",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="choices",
            field=models.ManyToManyField(related_name="answers", to="survey.choice"),
        ),
    ]
