# Generated by Django 4.2.13 on 2024-06-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0033_alter_session_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
