# Generated by Django 4.2.13 on 2024-06-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0035_fill_question_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
