# Generated by Django 5.1.14 on 2025-12-03 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0036_alter_question_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="survey.session",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="value",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="session",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="survey.survey",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="name",
            field=models.CharField(max_length=80),
        ),
    ]
