# Generated by Django 5.1.15 on 2026-01-14 15:53

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0037_alter_answer_session_alter_answer_value_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="questionset",
            name="precondition_tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Affiche ce groupe de questions si TOUS les signaux saisis sont émis",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Pré-condition",
            ),
        ),
    ]
