"""
Django settings for urbanvitaliz project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.humanize",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.admin",
    "hijack",
    "hijack.contrib.admin",
    "magicauth",
    "sass_processor",
    "markdownx",
    "tagging",
    "leaflet",
    "django_gravatar",
    "actstream",
    "notifications",
    "rest_framework",
    "csvexport",
    "urbanvitaliz.apps.home",
    "urbanvitaliz.apps.projects",
    "urbanvitaliz.apps.resources",
    "urbanvitaliz.apps.geomatics",
    "urbanvitaliz.apps.addressbook",
    "urbanvitaliz.apps.survey",
    "urbanvitaliz.apps.reminders",
    "urbanvitaliz.apps.communication",
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "sesame.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "hijack.middleware.HijackUserMiddleware",
]

ROOT_URLCONF = "urbanvitaliz.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.media",
                "django.contrib.messages.context_processors.messages",
                "urbanvitaliz.apps.projects.context_processors.is_switchtender_processor",
                "urbanvitaliz.apps.projects.context_processors.active_project_processor",
            ],
        },
    },
]


WSGI_APPLICATION = "urbanvitaliz.wsgi.application"

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "sesame.backends.ModelBackend",
]

# SESAME Configuration
SESAME_MAX_AGE = 60 * 60 * 24 * 10

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "Europe/Paris"

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "..", "static")

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "sass_processor.finders.CssFinder",
]

# UPLOAD

MEDIA_ROOT = os.path.join(BASE_DIR, "..", "media")
MEDIA_URL = "media/"

SASS_PRECISION = 8

SASS_PROCESSOR_INCLUDE_DIRS = [
    os.path.join(BASE_DIR, "urbanvitaliz/static/css"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email Configuration
EMAIL_FROM = "UrbanVitaliz <no-reply@urbanvitaliz.fr>"

# MagicAuth configuration
LOGIN_URL = "/login/"
LOGOUT_REDIRECT_URL = "login-redirect"
MAGICAUTH_FROM_EMAIL = EMAIL_FROM
MAGICAUTH_EMAIL_SUBJECT = "Connectez-vous à UrbanVitaliz ici"
MAGICAUTH_EMAIL_FIELD = "email"
MAGICAUTH_LOGGED_IN_REDIRECT_URL_NAME = "projects-redirect-user-to-project"
MAGICAUTH_EMAIL_UNKNOWN_CALLBACK = "urbanvitaliz.apps.home.utils.create_user"
MAGICAUTH_TOKEN_DURATION_SECONDS = 60 * 60 * 24 * 3

# MARKDOWNX
MARKDOWNX_MARKDOWN_EXTENSIONS = [
    "markdown.extensions.extra",
    "markdown_link_attr_modifier",
]

MARKDOWNX_MARKDOWN_EXTENSION_CONFIGS = {
    "markdown_link_attr_modifier": {
        "new_tab": "on",
        "no_referrer": "external_only",
        "auto_title": "on",
    },
}

# Tagging
FORCE_LOWERCASE_TAGS = True

# Session Settings
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 30 * 24 * 60 * 60  # 30d * 24h * 60m * 60s

# emails to use for notifications
TEAM_EMAILS = ["friches@beta.gouv.fr"]

# SENDINBLUE
SENDINBLUE_API_KEY = "NO-API-KEY-DEFINED"

# eof
