# Generated by Django 3.2.3 on 2022-02-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0002_emailtemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="name",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
