# Generated by Django 3.2.15 on 2022-09-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("communication", "0004_auto_20220506_0957"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name="emailtemplate",
            unique_together={("site", "name")},
        ),
    ]
