# Generated by Django 5.1.14 on 2025-12-03 10:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("blue", "Bleu"),
                            ("black", "Black"),
                            ("yellow", "Jaune"),
                            ("orange", "Orange"),
                            ("red", "Rouge"),
                            ("green", "Vert"),
                            ("violet", "Violet"),
                        ],
                        max_length=16,
                    ),
                ),
                ("icon", models.CharField(max_length=32)),
                ("deleted", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "catégorie",
                "verbose_name_plural": "catégories",
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public", models.BooleanField(blank=True, default=False)),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date de création",
                    ),
                ),
                ("tags", models.CharField(blank=True, default="", max_length=256)),
                ("title", models.CharField(max_length=128)),
                ("content", models.TextField()),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resources.category",
                    ),
                ),
                ("quote", models.CharField(default="", max_length=256)),
                ("subtitle", models.CharField(default="", max_length=128)),
                (
                    "updated_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="dernière modification",
                    ),
                ),
            ],
            options={
                "verbose_name": "ressource",
                "verbose_name_plural": "ressources",
            },
        ),
    ]
