# Generated by Django 5.1.14 on 2025-12-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0016_auto_20210809_1230"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="expires_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="date d'expiration"
            ),
        ),
    ]
