# Generated by Django 5.1.14 on 2025-12-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0019_resource_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Brouillon"), (1, "A relire"), (2, "Publié")],
                default=0,
                verbose_name="État",
            ),
        ),
        migrations.RemoveField(
            model_name="resource",
            name="public",
        ),
    ]
