# Generated by Django 5.1.14 on 2025-12-03 10:35

import django.db.models.manager
import recoco.apps.resources.models
from django.db import migrations


class Migration(migrations.Migration):
    replaces = [
        ("resources", "0025_auto_20220504_1538"),
        ("resources", "0026_rename_tags_resource_old_tags"),
    ]

    dependencies = [
        ("resources", "0024_bookmark_site"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="bookmark",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", recoco.apps.resources.models.BookmarkOnSiteManager()),
                (
                    "deleted_on_site",
                    recoco.apps.resources.models.DeletedBookmarkOnSiteManager(),
                ),
            ],
        ),
        migrations.AlterModelManagers(
            name="category",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", recoco.apps.resources.models.CategoryOnSiteManager()),
                (
                    "deleted_on_site",
                    recoco.apps.resources.models.DeletedCategoryOnSiteManager(),
                ),
            ],
        ),
        migrations.AlterModelManagers(
            name="resource",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", recoco.apps.resources.models.ResourceOnSiteManager()),
            ],
        ),
        migrations.RenameField(
            model_name="resource",
            old_name="tags",
            new_name="old_tags",
        ),
    ]
