# Generated by Django 4.2.16 on 2024-11-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0030_resource_site_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="imported_from",
            field=models.URLField(
                blank=True,
                help_text="l'URL depuis laquelle cette ressource a été importée",
                null=True,
                verbose_name="Importé depuis",
            ),
        ),
    ]
