# Generated by Django 5.1.15 on 2026-01-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0032_resourceaddon"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="support_orga",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
