# Generated by Django 5.2.13 on 2026-04-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0034_resourcerevisionmeta"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcerevisionmeta",
            name="kind",
            field=models.CharField(
                choices=[("modification", "Modification"), ("creation", "Création")],
                default="modification",
                max_length=20,
            ),
        ),
    ]
