# Generated by Django 3.2.13 on 2022-07-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="note",
            unique_together={("content_type", "object_id")},
        ),
    ]
