# Generated by Django 3.2.14 on 2022-08-02 08:48

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

import urbanvitaliz.apps.crm.models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("crm", "0002_alter_note_unique_together"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="note",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", urbanvitaliz.apps.crm.models.NoteOnSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name="note",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
            preserve_default=False,
        ),
    ]
