# Generated by Django 3.2.15 on 2022-10-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_auto_20220802_1048"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="sticky",
            field=models.BooleanField(default=False, verbose_name="Épingler"),
        ),
    ]
