# Generated by Django 3.2.15 on 2022-10-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_alter_note_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Titre de la note"
            ),
        ),
    ]
