# Generated by Django 3.2.15 on 2022-10-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_note_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="kind",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Appel Téléphonique"),
                    (1, "Email"),
                    (2, "Test utilisateur"),
                ],
                null=True,
                verbose_name="Type de contact",
            ),
        ),
    ]
