# Generated by Django 3.2.17 on 2023-03-21 14:28

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import taggit.managers
import urbanvitaliz.apps.crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("projects", "0077_alter_userprojectstatus_status"),
        ("taggit", "0005_auto_20220424_2025"),
        ("crm", "0008_note_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAnnotations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_annotations",
                        to="projects.project",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "project annotation",
                "verbose_name_plural": "project annotations",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                (
                    "on_site",
                    urbanvitaliz.apps.crm.models.ProjectAnnotationsOnSiteManager(),
                ),
            ],
        ),
    ]
