# Generated by Django 3.2.23 on 2024-01-23 17:10

from django.db import migrations


def _get_tag_mapping(apps):
    Tag = apps.get_model("taggit", "Tag")

    return {
        "crm_diag": Tag.objects.get(name__iexact="Diagnostic"),
        "crm_edl": Tag.objects.get(name__iexact="État des lieux"),
        "crm_contact": Tag.objects.get(name__iexact="Mise en relation"),
        "crm_general": Tag.objects.get(name__iexact="Général positif"),
    }


class Migration(migrations.Migration):
    def assign_new_tags(apps, schema_editor):
        TaggedItem = apps.get_model("taggit", "TaggedItem")

        tag_mapping = _get_tag_mapping(apps)

        for slug, tag in tag_mapping.items():
            TaggedItem.objects.filter(tag__slug=slug).update(tag=tag)

    def assign_old_tags(apps, schema_editor):
        Tag = apps.get_model("taggit", "Tag")
        TaggedItem = apps.get_model("taggit", "TaggedItem")

        tag_mapping = _get_tag_mapping(apps)

        for slug, tag in tag_mapping.items():
            old_tag = Tag.objects.get(slug=slug)
            TaggedItem.objects.filter(tag=tag).update(tag=old_tag)

    dependencies = [
        ("crm", "0009_project_annotations"),
        ("home", "0020_siteconfiguration_crm_available_tags"),
    ]

    operations = [
        migrations.RunPython(assign_new_tags, assign_old_tags),
    ]
