# Generated by Django 5.1.14 on 2025-12-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("home", "0018_add_reminder_interval"),
        ("home", "0019_alter_siteconfiguration_reminder_interval"),
    ]

    dependencies = [
        ("home", "0017_update_verbs"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="reminder_interval",
            field=models.IntegerField(
                default=42, help_text="en jours", verbose_name="Interval des rappels"
            ),
        ),
    ]
