# Generated by Django 3.2.23 on 2023-12-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_add_reminder_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="reminder_interval",
            field=models.IntegerField(
                default=42, help_text="en jours", verbose_name="Interval des rappels"
            ),
        ),
    ]
