# Generated by Django 3.2.23 on 2024-01-23 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0033_alter_session_project"),
        ("onboarding", "0005_alter_onboarding_form"),
        ("home", "0020_siteconfiguration_crm_available_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="onboarding",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="onboarding.onboarding",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="project_survey",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="survey.survey",
            ),
        ),
    ]
