# Generated by Django 3.2.23 on 2024-02-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_auto_20240123_1142"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="previous_login_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
