# Generated by Django 4.2.11 on 2024-03-15 09:30

from django.db import migrations, models
import recoco.apps.home.models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0023_auto_20240206_1216"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=recoco.apps.home.models.SiteConfiguration.logo_upload_path,
                verbose_name="Logo utilisé pour les emails automatiques",
            ),
        ),
    ]
