# Generated by Django 4.2.10 on 2024-03-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0033_alter_session_project"),
        ("home", "0023_auto_20240206_1216"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="onboarding_questions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Question présentées lors de la saisine",
                null=True,
                to="survey.question",
            ),
        ),
    ]
