# Generated by Django 4.2.11 on 2024-04-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_siteconfiguration_onboarding_questions"),
        ("home", "0025_siteconfiguration_legal_address"),
    ]

    operations = []
