# Generated by Django 5.0.3 on 2024-04-23 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0026_merge_20240422_0744"),
        ("home", "0026_merge_20240422_1101"),
    ]

    operations = []
