# Generated by Django 4.2.13 on 2024-05-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0027_merge_20240423_1117"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="legal_owner",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Propriétaire légal"
            ),
        ),
    ]


# eof
