# Generated by Django 5.1.14 on 2025-12-03 10:37

import recoco.apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0027_merge_20240423_1117"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="legal_owner",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Propriétaire légal"
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description de 2 à 5 phrases, notamment utilisée dans les emails d'invitation",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="logo_large",
            field=models.ImageField(
                blank=True,
                help_text="Utilisé par exemple pour la barre de navigation. Veuillez fournir une image avec un fond transparent (png)",
                null=True,
                upload_to=recoco.apps.home.models.SiteConfiguration.logo_large_upload_path,
                verbose_name="Logo complet",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="logo_small",
            field=models.ImageField(
                blank=True,
                help_text="Utilisé en cas de manque d'espace. Format carré recommandé, avec un fond transparent (png)",
                null=True,
                upload_to=recoco.apps.home.models.SiteConfiguration.logo_small_upload_path,
                verbose_name="Logo réduit",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="email_logo",
            field=models.ImageField(
                blank=True,
                help_text="Veuillez fournir une image d'une largeur maximale de 600 pixels et d'un ratio de 4:3.",
                null=True,
                upload_to=recoco.apps.home.models.SiteConfiguration.logo_email_upload_path,
                verbose_name="Logo utilisé pour les emails automatiques",
            ),
        ),
    ]
