# Generated by Django 4.2.13 on 2024-06-18 16:58

from django.db import migrations, models
import recoco.apps.home.models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0029_siteconfiguration_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="logo_large",
            field=models.ImageField(
                blank=True,
                help_text="Utilisé par exemple pour la barre de navigation. Veuillez fournir une image avec un fond transparent (png)",
                null=True,
                upload_to=recoco.apps.home.models.SiteConfiguration.logo_large_upload_path,
                verbose_name="Logo complet",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="logo_small",
            field=models.ImageField(
                blank=True,
                help_text="Utilisé en cas de manque d'espace. Format carré recommandé, avec un fond transparent (png)",
                null=True,
                upload_to=recoco.apps.home.models.SiteConfiguration.logo_small_upload_path,
                verbose_name="Logo réduit",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="email_logo",
            field=models.ImageField(
                blank=True,
                help_text="Veuillez fournir une image d'une largeur maximale de 600 pixels et d'un ratio de 4:3.",
                null=True,
                upload_to=recoco.apps.home.models.SiteConfiguration.logo_email_upload_path,
                verbose_name="Logo utilisé pour les emails automatiques",
            ),
        ),
    ]
