# Generated by Django 4.2.11 on 2024-07-16 12:10

from django.db import migrations, models
import recoco.apps.home.models
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        (
            "home",
            "0028_siteconfiguration_legal_owner_squashed_0030_siteconfiguration_logo_large_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="contact_form_recipient",
            field=models.EmailField(
                max_length=254, verbose_name="Adresse de contact affichée sur le site"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="crm_available_tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='Liste de tags séparés par une virgule. Si le tag contient plusieurs mots les encadrer par des guillemets.Attention, veillez à ne pas retirer un tag utilisé dans un projet, celui-ci ne pourra plus être retiré depuis le CRM. ex: "signature convention", diagnostic, "lancement travaux"',
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags d'impact disponibles sur les projets dans le CRM",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description de 2 à 5 phrases, notamment utilisée dans les emails d'invitation",
                null=True,
                verbose_name="Description du service",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="email_logo",
            field=models.ImageField(
                blank=True,
                help_text="Format rectangulaire recommandé, avec un fond transparent (png)",
                null=True,
                upload_to=recoco.apps.home.models.SiteConfiguration.logo_email_upload_path,
                verbose_name="Logo utilisé pour les emails automatiques",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="legal_address",
            field=models.CharField(
                blank=True,
                help_text="L'adresse postale est notamment affichée en bas des emails automatiques et dans les pages légales.",
                max_length=100,
                null=True,
                verbose_name="Adresse postale",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="legal_owner",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Entité responsable légalement du service",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="logo_large",
            field=models.ImageField(
                blank=True,
                help_text="Utilisé par exemple pour la barre de navigation. Format rectangulaire recommandé, avec un fond transparent (png)",
                null=True,
                upload_to=recoco.apps.home.models.SiteConfiguration.logo_large_upload_path,
                verbose_name="Logo complet",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="reminder_interval",
            field=models.IntegerField(
                default=42,
                help_text="en jours",
                verbose_name="Fréquence des emails de rappel",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="sender_email",
            field=models.EmailField(
                max_length=254,
                verbose_name="Adresse de contact affichée dans les emails automatiques",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="sender_name",
            field=models.CharField(
                help_text="Nom du service affiché comme expéditeur des emails",
                max_length=30,
                verbose_name="Expéditeur des emails automatiques",
            ),
        ),
    ]
