# Generated by Django 4.2.13 on 2024-10-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0032_siteconfiguration_accept_handover_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="main_topic",
            field=models.CharField(
                blank=True,
                help_text="Décrivez le plus brièvement possible la thématique de ce portail",
                null=True,
                verbose_name="Thématique principale",
            ),
        ),
    ]
