# Generated by Django 5.1.14 on 2025-12-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("home", "0033_siteconfiguration_main_topic"),
        ("home", "0034_siteconfiguration_crisp_token"),
    ]

    dependencies = [
        ("home", "0032_siteconfiguration_accept_handover_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="main_topic",
            field=models.CharField(
                blank=True,
                help_text="Décrivez le plus brièvement possible la thématique de ce portail",
                null=True,
                verbose_name="Thématique principale",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="crisp_token",
            field=models.CharField(
                blank=True, null=True, verbose_name="Clé pour activer CRISP"
            ),
        ),
    ]
