# Generated by Django 4.2.19 on 2025-03-20 15:14

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        (
            "home",
            "0033_siteconfiguration_main_topic_squashed_0034_siteconfiguration_crisp_token",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="accept_handover",
            field=models.BooleanField(
                default=True,
                verbose_name="Accepter des propositions de dossiers venant d'autres portails",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="crm_available_tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='Liste de tags séparés par une virgule. Si le tag contient plusieurs mots les encadrer par des guillemets.Attention, veillez à ne pas retirer un tag utilisé dans un dossier, celui-ci ne pourra plus être retiré depuis le CRM. ex: "signature convention", diagnostic, "lancement travaux"',
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags d'impact disponibles sur les dossiers dans le CRM",
            ),
        ),
    ]
