# Generated by Django 4.2.19 on 2025-02-25 09:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("home", "0034_siteconfiguration_crisp_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLoginEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("logged_in", "User logged in"),
                            ("logged_out", "User logged out"),
                        ],
                        editable=False,
                        max_length=64,
                    ),
                ),
                ("ip", models.GenericIPAddressField(null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_entries",
                        to="home.userprofile",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal des connexions",
                "verbose_name_plural": "Journal des connexions",
                "ordering": ("-created",),
            },
        ),
    ]
