# Generated by Django 4.2.19 on 2025-05-06 06:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0037_advisoraccessrequest"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="advisoraccessrequest",
            managers=[
                ("on_site", django.db.models.manager.Manager()),
            ],
        ),
    ]
