# Generated by Django 4.2.19 on 2025-06-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0037_advisoraccessrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoraccessrequest",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Commentaire laissé par le conseiller lors de la demande d'accès",
                null=True,
            ),
        ),
    ]
