# Generated by Django 5.1.11 on 2025-07-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0038_advisoraccessrequest_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="needs_profile_update",
            field=models.BooleanField(default=False),
        ),
    ]
