# Generated by Django 5.1.11 on 2025-06-27 07:17

from django.db import migrations
from recoco.verbs import Project


def notification_update(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")

    mapping = [
        ("a rejoint le dossier", "a accepté l'invitation sur le dossier"),
        (
            "a déposé un nouveau dossier, qui est en attente de validation",
            Project.SUBMITTED_BY,
        ),
        # ("a rejoint le dossier", Project.),
    ]

    for old, new in mapping:
        for notification in Notification.objects.filter(verb__icontains=old):
            print(notification.pk, notification.verb)
            notification.verb = new
            notification.save()

    assert False


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0038_advisoraccessrequest_comment"),
    ]

    operations = [
        migrations.RunPython(notification_update, migrations.RunPython.noop),
    ]
