# Generated by Django 4.2.19 on 2025-05-06 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0038_alter_advisoraccessrequest_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="advisoraccessrequest",
            managers=[],
        ),
    ]
