# Generated by Django 5.1.15 on 2026-02-03 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0038_advisoraccessrequest_comment"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="previous_login_at",
            new_name="previous_activity_at",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="nb_deletion_warnings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="previous_activity_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users_previous_activity",
                to="sites.site",
                verbose_name="Dernier site consulté",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="previous_deletion_warning_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="deleted",
            new_name="disabled",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="deleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
