# Generated by Django 5.1.15 on 2026-02-04 13:21

from django.db import migrations
from django.db.models import Subquery, OuterRef, Count


def fill_previous_activity_site(apps, schema_editor):
    UserProfile = apps.get_model("home", "UserProfile")

    Site = apps.get_model("sites", "Site")
    counted_sites_profiles = UserProfile.objects.annotate(count_site=Count("sites"))

    counted_sites_profiles.filter(count_site=1).update(
        previous_activity_site=Subquery(
            Site.objects.filter(userprofile=OuterRef("pk")).values("pk")[:1]
        )
    )

    Action = apps.get_model("actstream", "Action")
    count = 0
    undefined_site = []
    for profile in counted_sites_profiles.filter(count_site__gt=1):
        found = False

        last_trace = (
            Action.objects.filter(actor_object_id=profile.user.id)
            .order_by("-timestamp")
            .first()
        )
        if last_trace is not None:
            profile.previous_activity_site_id = last_trace.site_id
            found = True

        last_msg = (
            profile.user.project_messages.annotate(count=Count("project__sites"))
            .filter(count=1)
            .order_by("-created")
            .first()
        )
        if last_msg is not None:
            profile.previous_activity_site_id = last_msg.project.sites.first().id
            found = True

        projects_as_member = profile.user.projectmember_set.values_list(
            "project__sites", flat=True
        ).distinct()
        if not found and projects_as_member.count() == 1:
            profile.previous_activity_site_id = projects_as_member.first()
            found = True

        projects_as_submittee = profile.user.projects_submitted.values_list(
            "sites", flat=True
        ).distinct()
        if not found and projects_as_submittee.count() == 1:
            profile.previous_activity_site_id = projects_as_submittee.first()
            found = True

        projects_as_advisor = profile.user.projects_switchtended_per_site.values_list(
            "site", flat=True
        ).distinct()
        if not found and projects_as_advisor.count() == 1:
            profile.previous_activity_site_id = projects_as_advisor.first()
            found = True

        if not found:
            count += 1
            undefined_site.append(profile)
            profile.previous_activity_site = profile.sites.first()

        profile.save()

    counted_sites_profiles.filter(
        previous_activity_site__isnull=True, count_site=0
    ).update(previous_activity_site_id=1)

    print(
        f"{count} users with no defined site. Random site set up but you may want to modify. Active users will have the field updated anyway"
    )
    for p in undefined_site:
        print(p.user.email)


def unfill_previous_activity_site(apps, schema_editor):
    UserProfile = apps.get_model("home", "UserProfile")
    UserProfile.objects.update(previous_activity_site_id=None)


class Migration(migrations.Migration):
    dependencies = [
        (
            "home",
            "0039_rename_previous_login_at_userprofile_previous_activity_at_and_more",
        ),
        ("actstream", "0004_add_multisite_support"),
        ("sites", "0002_alter_domain_unique"),
        ("conversations", "0007_auto_20251230_1707"),
        ("projects", "0116_alter_projectsite_status"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(
            fill_previous_activity_site,
            unfill_previous_activity_site,
        ),
    ]
