# Generated by Django 5.1.15 on 2026-02-04 13:21

from django.db import migrations
from django.db.models import Subquery, OuterRef, F, Q
from tqdm import tqdm


def fill_previous_activity_site(apps, schema_editor):
    UserProfile = apps.get_model("home", "UserProfile")
    User = apps.get_model("auth", "User")

    # ensures there is no None previous_activity_at
    (
        UserProfile.objects.filter(
            Q(previous_activity_at__isnull=True)
            | Q(previous_activity_at__lt=F("user__last_login"))
        ).update(
            previous_activity_at=Subquery(
                User.objects.filter(pk=OuterRef("user_id")).values_list("last_login")[
                    :1
                ]
            )
        )
    )
    UserProfile.objects.filter(previous_activity_at__isnull=True).update(
        previous_activity_at=Subquery(
            User.objects.filter(pk=OuterRef("user_id")).values_list("date_joined")[:1]
        )
    )

    # tries to set later dates based on activity
    Action = apps.get_model("actstream", "Action")
    for profile in tqdm(UserProfile.objects.all()):
        last_trace = (
            Action.objects.filter(actor_object_id=profile.user.id)
            .filter(timestamp__gt=profile.previous_activity_at)
            .order_by("-timestamp")
            .first()
        )
        if last_trace is not None:
            profile.previous_activity_at = last_trace.timestamp

        last_msg = (
            profile.user.project_messages.filter(
                created__gt=profile.previous_activity_at
            )
            .order_by("-created")
            .first()
        )
        if last_msg is not None:
            profile.previous_activity_at = last_msg.created

        profile.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "home",
            "0040_fill_profile_previous_activity_site",
        ),
        ("actstream", "0004_add_multisite_support"),
        ("conversations", "0007_auto_20251230_1707"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(
            fill_previous_activity_site,
            migrations.RunPython.noop,
        ),
    ]
