# Generated by Django 5.1.15 on 2026-02-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0040_fill_profile_previous_activity_site"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="deleted",
            new_name="disabled",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="deleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
