# Generated by Django 5.1.15 on 2026-02-27 14:38
from django.conf import settings
from django.db import migrations
from django.db.models import (
    Subquery,
    OuterRef,
    When,
    Case,
    Value,
    IntegerField,
    Exists,
    Q,
    F,
)
from django.db.models.fields import CharField
from django.db.models.functions import Cast

from recoco import verbs


def specialize_verbs(apps, schema_editor):
    Action = apps.get_model("actstream", "Action")
    Document = apps.get_model("projects", "Document")
    Project = apps.get_model("projects", "Project")
    Group = apps.get_model("auth", "Group")
    Site = apps.get_model("sites", "Site")

    # Document.ADDED
    submitter_type_sq = Subquery(
        Document.objects.annotate(
            doc_type=Case(
                When(the_file__isnull=False, then=Value("FILE")),
                When(the_link__isnull=False, then=Value("LINK")),
                default=Value(""),
            )
        )
        .filter(
            id=Cast(OuterRef("action_object_object_id"), output_field=IntegerField())
        )
        .values_list("doc_type", flat=True)[:1]
    )

    for site in Site.objects.all():
        with settings.SITE_ID.override(site.pk):
            query_added = Action.objects.annotate(
                action_document_type=submitter_type_sq
            ).filter(verb="a ajouté un lien ou un document")

            print(
                f"Transforming some Document.ADDED to Document.ADDED_FILE in site {site.name}"
            )
            query_added.filter(action_document_type="FILE").update(
                verb=verbs.Document.ADDED_FILE
            )
            print(
                f"Transforming some Document.ADDED to Document.ADDED_LINK in site {site.name}"
            )
            query_added.filter(action_document_type="LINK").update(
                verb=verbs.Document.ADDED_LINK
            )

    # Project.SUBMITTED_BY
    submitted_verbs = [
        "a été déposé",
        "a déposé un nouveau dossier, qui est en attente de validation",
        "a déposé un nouveau dossier, en attente de validation",
    ]
    project_sq = Project.objects.filter(
        id=Cast(OuterRef("action_object_object_id"), output_field=IntegerField())
    )
    submitter_sq = Subquery(project_sq.values_list("submitted_by", flat=True)[:1])
    is_advisor_sq = Exists(
        Group.objects.filter(
            Q(name__contains="staff") | Q(name__contains="admin")
        ).filter(user=OuterRef("submitted_by"))
    )
    submitter_type_sq = Subquery(
        project_sq.annotate(
            submitted_by_type=Case(
                When(is_advisor_sq, then=Value("ADVISOR")), default=Value("MEMBER")
            )
        ).values_list("submitted_by_type", flat=True)[:1]
    )

    for site in Site.objects.all():
        with settings.SITE_ID.override(site.pk):
            query_submitted_by_advisor = (
                Action.objects.filter(verb__in=submitted_verbs)
                .annotate(
                    project_submitted_by=submitter_sq,
                    project_submitted_by_type=submitter_type_sq,
                )
                .filter(project_submitted_by_type="ADVISOR")
                .exclude(
                    actor_object_id=Cast(
                        F("project_submitted_by"), output_field=CharField()
                    )
                )
            )

            print(
                f"Transforming some Project.SUBMITTED and Project.SUBMITTED_BY to Project.SUBMITTED_BY_ADVISOR in site {site.name}"
            )
            query_submitted_by_advisor.update(
                verb=verbs.Project.SUBMITTED_BY_ADVISOR,
                actor_object_id=Cast(
                    F("project_submitted_by"), output_field=CharField()
                ),
            )

            print("Creating Project.INVITATION_OWNER")
            new_actions = []
            for action in query_submitted_by_advisor:
                new_actions.append(
                    Action(
                        verb=verbs.Project.INVITATION_OWNER,
                        actor_object_id=action.project_submitted_by,
                        actor_content_type_id=action.actor_content_type_id,  # quick way to acces user content type id
                        action_object=action.actor,
                        target=action.target,
                        site=action.site,
                    )
                )
            Action.objects.bulk_create(new_actions)

            query_submitted_by_advisor.update(
                verb=verbs.Project.SUBMITTED_BY_ADVISOR,
                actor_object_id=F("project_submitted_by"),
            )


def merge_verbs(apps, schema_editor):
    Action = apps.get_model("actstream", "Action")
    Site = apps.get_model("sites", "Site")

    for site in Site.objects.all():
        with settings.SITE_ID.override(site.pk):
            # Document.ADDED
            Action.objects.filter(verb=verbs.Document.ADDED_FILE).update(
                verb="a ajouté un lien ou un document"
            )
            Action.objects.filter(verb=verbs.Document.ADDED_LINK).update(
                verb="a ajouté un lien ou un document"
            )

            # Project.SUBMITTED_BY
            to_update = []
            for action in Action.objects.filter(
                verb=verbs.Project.SUBMITTED_BY_ADVISOR
            ):
                action.verb = (
                    "a déposé un nouveau dossier, qui est en attente de validation"
                )
                action.actor = action.target.owner
                to_update.append(action)
            Action.objects.bulk_update(to_update, ["verb", "actor_object_id"])
            Action.objects.filter(verb=verbs.Project.INVITATION_OWNER).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0041_fill_profile_previous_activity_at"),
        ("projects", "0116_alter_projectsite_status"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(
            specialize_verbs,
            merge_verbs,
        ),
    ]
