# Generated by Django 5.1.15 on 2026-03-13 17:04

import django.db.models.manager
import recoco.apps.home.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0042_notification_splits"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="userprofile",
            managers=[
                ("all", django.db.models.manager.Manager()),
                ("on_site", recoco.apps.home.models.UserProfileOnSiteManager()),
            ],
        ),
    ]
