# Generated by Django 5.1.15 on 2026-03-16 13:33

import django.db.models.manager
import recoco.apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0042_notification_splits"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="userprofile",
            managers=[
                ("all", django.db.models.manager.Manager()),
                ("on_site", recoco.apps.home.models.UserProfileOnSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="enabled_plugins",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste des plugins activés sur ce portail",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="schema_name",
            field=models.SlugField(
                blank=True,
                help_text="Le schema PgSQL pour ce portail.",
                null=True,
                unique=True,
            ),
        ),
    ]
