# Generated by Django 5.1.15 on 2026-05-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0043_alter_userprofile_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="stopped_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Si renseignée, indique la date à laquelle le portail a été arrêté.",
                null=True,
                verbose_name="Date d'arrêt du portail",
            ),
        ),
    ]
