# Generated by Django 5.2.14 on 2026-06-03 13:28

from django.db import migrations


def set_cookie_consent(apps, schema_editor):
    Cookie = apps.get_model("cookie_consent", "Cookie")
    CookieGroup = apps.get_model("cookie_consent", "CookieGroup")

    group, _ = CookieGroup.objects.get_or_create(
        varname="preferences",
        name="Préférences",
        description="Sauvegarde des préférences de l'utilisateur pour simplifier son usage de l'application",
    )
    Cookie.objects.get_or_create(
        cookiegroup=group,
        name="enable-sesame",
        description="Garde trace de la dernière personne connectée pour autoriser la connexion par lien magique pendant la durée de vie de cookie pour la personne",
    )


def unset_cookie_consent(apps, schema_editor):
    Cookie = apps.get_model("cookie_consent", "Cookie")
    Cookie.objects.filter(name="enable-sesame").delete()

    CookieGroup = apps.get_model("cookie_consent", "CookieGroup")
    group = CookieGroup.objects.filter(varname="preferences").first()
    if group is not None and not group.cookie_set.exists():
        group.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0043_alter_userprofile_managers"),
    ]

    operations = [migrations.RunPython(set_cookie_consent, unset_cookie_consent)]
