# Generated by Django 5.2.14 on 2026-06-05 14:46

import django.db.models.manager
from allauth.mfa.models import Authenticator

import recoco.apps.home.models

from django.db import migrations, models
from django.db.models import Q, OuterRef, Subquery, Exists


def default_2fa_for_admin_staff(apps, schema_editor):
    UserProfile = apps.get_model("home", "UserProfile")
    need_2fa = UserProfile.all.filter(
        Q(user__groups__name__contains="staff")
        | Q(user__groups__name__contains="admin")
    )
    need_2fa.update(requires_2fa=True)

    need_login_by_code = need_2fa.exclude(
        Exists(
            Subquery(
                Authenticator.objects.filter(type="totp", user_id=OuterRef("user_id"))
            )
        )
    )
    need_login_by_code.update(login_with_code=True)


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0045_siteconfiguration_plugin_fields"),
        ("mfa", "0003_authenticator_type_uniq"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="login_with_code",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="requires_2fa",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelManagers(
            name="userprofile",
            managers=[
                ("all", django.db.models.manager.Manager()),
                ("objects", recoco.apps.home.models.UserProfileManager()),
                ("on_site", recoco.apps.home.models.UserProfileOnSiteManager()),
            ],
        ),
        migrations.RunPython(
            default_2fa_for_admin_staff,
            migrations.RunPython.noop,
        ),
    ]
