# Generated by Django 5.2.15 on 2026-07-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0045_siteconfiguration_plugin_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="embed_allowed_origins",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste des origines (ex: https://exemple.gouv.fr) autorisées à intégrer ce portail dans une iframe (embed). Admin uniquement.",
            ),
        ),
    ]
