# Generated by Django 5.2.17 on 2026-08-21 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0046_userprofile_login_with_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "base_manager_name": "all",
                "verbose_name": "profil utilisateur",
                "verbose_name_plural": "profils utilisateurs",
            },
        ),
    ]
