# Generated by Django 5.2.16 on 2026-08-18 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0046_userprofile_login_with_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="sender_email",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="sender_name",
        ),
    ]
