# Generated by Django 5.2.16 on 2026-07-31 09:17

from django.db import migrations

from recoco.utils import make_group_name_for_site

GROUP_NAME = "m2m_partner"
PERM_CODENAME = "use_m2m_api"


def create_m2m_partner_groups(apps, schema_editor):
    """Create the m2m partner group of each site, and give it the api perm"""
    Site = apps.get_model("sites", "Site")
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    GroupObjectPermissionOnSite = apps.get_model("home", "GroupObjectPermissionOnSite")

    db_alias = schema_editor.connection.alias

    site_ct, _ = ContentType.objects.using(db_alias).get_or_create(
        app_label="sites", model="site"
    )

    # the permission itself is created by our post_migrate receiver, which only
    # runs once all the migrations are applied
    permission, _ = Permission.objects.using(db_alias).get_or_create(
        codename=PERM_CODENAME,
        content_type=site_ct,
        defaults={"name": "Can use the machine to machine API"},
    )

    for site in Site.objects.using(db_alias).all():
        group, _ = Group.objects.using(db_alias).get_or_create(
            name=make_group_name_for_site(GROUP_NAME, site)
        )
        GroupObjectPermissionOnSite.objects.using(db_alias).get_or_create(
            group=group,
            permission=permission,
            content_type=site_ct,
            object_pk=str(site.pk),
            site=site,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0046_userprofile_login_with_code"),
        ("sites", "0002_alter_domain_unique"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    # not reversed: dropping the groups would drop the partners along with them
    operations = [
        migrations.RunPython(create_m2m_partner_groups, migrations.RunPython.noop)
    ]
