# Generated by Django 5.2.17 on 2026-08-26 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0047_alter_userprofile_options"),
        ("home", "0047_embed_allowed_origins"),
    ]

    operations = []
