# Generated by Django 5.2.17 on 2026-09-07 11:11

import phonenumber_field.modelfields
import recoco.apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0049_remove_siteconfiguration_sender_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="dpo_contact_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Adresse du délégué à la protection des données (DPO) affichée sur le site",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text="Format carré (16x16) et avec un fond transparent (PNG)",
                null=True,
                upload_to=recoco.apps.home.models.SiteConfiguration.favicon_upload_path,
                verbose_name="Image utilisée dans l'affichage navigateur des onglets ou lors de partage du lien du site",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="gdpr_purposes",
            field=models.TextField(
                blank=True,
                help_text="Description des finalités de traitement des données personnelles sur ce portail",
                null=True,
                verbose_name="Finalités du traitement au sens du RGPD",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="legal_owner_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Représentant légal (prénom, nom, fonction)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="legal_phone_no",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Numéro de téléphone de l'organisation",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="target_audience",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Bénéficiaires du service",
            ),
        ),
    ]
