# Generated by Django 5.2.17 on 2026-09-30 10:38

from django.db import migrations
from django.db.models import Exists, Subquery, OuterRef


def default_2fa_for_groups(apps, schema_editor):
    UserProfile = apps.get_model("home", "UserProfile")
    Authenticator = apps.get_model("mfa", "Authenticator")
    group_regex = r".*(staff|admin|advisor)$"
    need_2fa = UserProfile.all.filter(user__groups__name__regex=group_regex)
    need_2fa.update(requires_2fa=True)

    need_login_by_code = need_2fa.exclude(
        Exists(
            Subquery(
                Authenticator.objects.filter(type="totp", user_id=OuterRef("user_id"))
            )
        )
    )
    need_login_by_code.update(login_with_code=True)


def no_required_2fa_for_advisors(apps, schema_editor):
    UserProfile = apps.get_model("home", "UserProfile")
    stop_login_by_code = UserProfile.objects.filter(
        user__groups__name__regex=".*advisor$"
    )
    stop_login_by_code.update(requires_2fa=False)


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0049_remove_siteconfiguration_sender_email"),
        ("mfa", "0003_authenticator_type_uniq"),
    ]

    operations = [
        migrations.RunPython(default_2fa_for_groups, no_required_2fa_for_advisors),
    ]
