# Generated by Django 5.2.17 on 2026-09-09 10:44

import phonenumber_field.modelfields
import recoco.apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0050_siteconfiguration_dpo_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="contact_form_recipient",
            field=models.EmailField(
                help_text="Format attendu : nom@domaine.fr",
                max_length=254,
                verbose_name="E-mail de contact affiché sur le site et dans les e-mails automatiques",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description de 1 à 3 phrases.\nPar exemple : UrbanVitaliz est un service gratuit du Cerema et du Ministère de la Transition Écologique. Il oriente les collectivités dans leurs projets de réhabilitation de fonciers à l’abandon (friches industrielles, ferroviaires, d'activité, d'habitation etc), en associant les acteurs publics locaux.",
                null=True,
                verbose_name="Description du service",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="dpo_contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Format attendu : nom@domaine.fr",
                max_length=254,
                null=True,
                verbose_name="Adresse e-mail du DPO",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="email_logo",
            field=models.ImageField(
                blank=True,
                help_text="Format supporté : PNG avec fond transparent. Format recommandé : rectangulaire horizontal.",
                null=True,
                upload_to=recoco.apps.home.models.SiteConfiguration.logo_email_upload_path,
                verbose_name="Logo dans les e-mails automatiques",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text="Format supporté : PNG avec fond transparent. Format recommandé : carré, sans texte. Taille maximum : 192 * 192 px.",
                null=True,
                upload_to=recoco.apps.home.models.SiteConfiguration.favicon_upload_path,
                verbose_name="Favicon",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="gdpr_purposes",
            field=models.TextField(
                blank=True,
                help_text="Par exemple :\n- principalement, le suivi et l’accompagnement des demandeurs (essentiellement collectivités mais aussi associations, entreprises ou particuliers) dans leurs projets de réhabilitation de friche ;\n- l’orientation de ces demandeurs vers les bons dispositifs, interlocuteurs et financements en fonction de leur situation ;\n- la réalisation d’études quantitatives et d’analyses sur les demandes déposées et les recommandations émises, permettant d’évaluer les besoins des demandeurs, et d’améliorer les accompagnements dispensés.",
                null=True,
                verbose_name="Finalités du traitement des données",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="legal_address",
            field=models.CharField(
                blank=True,
                help_text="L'adresse postale est notamment affichée en bas des emails automatiques et dans les pages légales. Format attendu : numéro et libellé de rue, code postal et commune",
                max_length=100,
                null=True,
                verbose_name="Adresse postale complète",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="legal_owner",
            field=models.CharField(
                blank=True,
                help_text="Par exemple : Cerema",
                max_length=100,
                null=True,
                verbose_name="Entité légalement responsable du service",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="legal_owner_name",
            field=models.CharField(
                default="Etienne Crépon, directeur général du CEREMA",
                help_text="Prénom, NOM, fonction",
                max_length=100,
                verbose_name="Représentant ou représentante légale",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="legal_phone_no",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Format attendu : +33102030405",
                max_length=128,
                null=True,
                region=None,
                verbose_name="Numéro de téléphone de l'organisation",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="logo_large",
            field=models.ImageField(
                blank=True,
                help_text="Format supporté : PNG avec fond transparent. Format recommandé : rectangulaire horizontal.",
                null=True,
                upload_to=recoco.apps.home.models.SiteConfiguration.logo_large_upload_path,
                verbose_name="Logo complet",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="logo_small",
            field=models.ImageField(
                blank=True,
                help_text="Format supporté : PNG avec fond transparent. Format recommandé : carré, sans texte.",
                null=True,
                upload_to=recoco.apps.home.models.SiteConfiguration.logo_small_upload_path,
                verbose_name="Logo réduit",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="main_topic",
            field=models.CharField(
                blank=True,
                help_text="Décrivez le plus brièvement possible la thématique de ce portail. \nPar exemple: Revitalisation des friches",
                null=True,
                verbose_name="Thématique principale",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="reminder_interval",
            field=models.IntegerField(
                default=42,
                help_text="En jours",
                verbose_name="Fréquence des emails de rappel",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="sender_name",
            field=models.CharField(
                help_text="Nom du service affiché comme expéditeur des e-mails",
                max_length=30,
                verbose_name="Nom de l'expéditeur des e-mails automatiques",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="target_audience",
            field=models.CharField(
                blank=True,
                help_text="Exemple : agents et élus de collectivités, d'association ou d'entreprises porteuses d'une projet de réhabilitation de friche, agents de l'Etat et autres établissements publics",
                max_length=150,
                null=True,
                verbose_name="Bénéficiaires du service",
            ),
        ),
    ]
