# Generated by Django 5.2.17 on 2026-09-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0051_alter_siteconfiguration_contact_form_recipient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="legal_owner_name",
            field=models.CharField(
                blank=True,
                help_text="Prénom, NOM, fonction",
                max_length=100,
                null=True,
                verbose_name="Représentant ou représentante légale",
            ),
        ),
    ]
