# Generated by Django 3.2.18 on 2023-11-02 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="date et heure de création",
            ),
        ),
    ]
