# Generated by Django 5.1.11 on 2025-06-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
