# Generated by Django 5.1.11 on 2025-06-25 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("ml", "0003_summary_created_summary_modified_comparison"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="summary",
            unique_together={("content_type", "object_id", "config", "prompt")},
        ),
    ]
