# Generated by Django 3.2.3 on 2021-08-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addressbook", "0002_auto_20210720_0948"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="mobile_no",
            field=models.CharField(blank=True, max_length=20, verbose_name="GSM"),
        ),
    ]
