# Generated by Django 3.2.3 on 2021-08-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addressbook", "0003_contact_mobile_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="division",
            field=models.CharField(blank=True, max_length=100, verbose_name="Fonction"),
        ),
    ]
