# Generated by Django 3.2.17 on 2023-03-20 13:21

import django.db.models.manager
import urbanvitaliz.apps.addressbook.models
from django.db import migrations, models


def update_organization_with_its_current_site(apps, schema_editor):
    Organization = apps.get_model("addressbook", "Organization")
    for organization in Organization.objects.all():
        contact = organization.contacts.first()
        if not contact:
            continue

        organization.sites.add(contact.site)


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("addressbook", "0005_auto_20220510_1034"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="organization",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                (
                    "on_site",
                    urbanvitaliz.apps.addressbook.models.OrganizationOnSiteManager(),
                ),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="sites",
            field=models.ManyToManyField(related_name="organizations", to="sites.Site"),
        ),
        migrations.RunPython(
            update_organization_with_its_current_site,
            lambda x, y: None,
        ),
    ]


# eof
