# Generated by Django 3.2.18 on 2023-05-29 14:35

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("addressbook", "0006_organization_sites"),
    ]

    operations = [TrigramExtension()]
