# Generated by Django 3.2.18 on 2023-06-14 15:09

from django.db import migrations


def assign_org_sites_from_user_profiles(apps, schema_editor):
    UserProfile = apps.get_model("home", "UserProfile")

    for profile in UserProfile.objects.all():
        org = profile.organization
        if org:
            for site in profile.sites.all():
                org.sites.add(site)


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
        ("addressbook", "0007_activate_trm"),
    ]

    operations = [
        migrations.RunPython(assign_org_sites_from_user_profiles, lambda x, y: None),
    ]
