# Generated by Django 3.2.19 on 2023-06-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geomatics", "0004_alter_department_region"),
        ("addressbook", "0008_assign_orgs_to_sites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                related_name="organizations",
                to="geomatics.Department",
                verbose_name="Départements concernés",
            ),
        ),
    ]
