# Generated by Django 4.2.13 on 2024-09-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geomatics", "0004_alter_department_region"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="commune",
            unique_together={("insee", "postal")},
        ),
    ]
