# Generated by Django 5.2.15 on 2026-07-14 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geomatics", "0005_alter_commune_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "pays",
                "verbose_name_plural": "pays",
            },
        ),
        migrations.AddField(
            model_name="region",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regions",
                to="geomatics.country",
            ),
        ),
    ]
