# Geomatics i18n
#
# Adds a surrogate `id` to Region/Department: an ordinary, identity-backed
# bigint column, not yet the primary key.
#
# This has to be its own, ordinary migration - not folded into the next
# one's SeparateDatabaseAndState - specifically so that migration's
# RunPython can reference `id` through the ORM (apps.get_model(...)). A
# RunPython inside SeparateDatabaseAndState only ever sees the project
# state as of *before* that migration (state_operations are tracked
# separately from database_operations), so if `id` were introduced in the
# same migration that repoints every dependent FK onto it, the ORM
# wouldn't know the field exists yet even though the column is really
# there - Django would raise FieldError. Applying this one first makes
# `id` part of the tracked state that the next migration's RunPython
# builds on.
#
# The column is created via raw SQL rather than a plain `AddField`, and
# described to Django as a `BigIntegerField` rather than a `BigAutoField`:
# Django's schema editor emits "PRIMARY KEY" for *any* AutoField column it
# adds, regardless of the `primary_key` kwarg passed to it (AutoField's own
# check() asserts "AutoFields must set primary_key=True", and add_field
# honors that unconditionally - confirmed via `sqlmigrate`, which showed
# `ADD COLUMN "id" bigint NOT NULL PRIMARY KEY ...` even with
# `primary_key=False` explicitly set). A *non-pk* auto-incrementing column
# therefore can't be created as an AutoField at all; it becomes a real
# `BigAutoField(primary_key=True)` in the next migration, once every
# dependent has moved off `code`.
#
# Uniqueness is backed by a plain `CREATE UNIQUE INDEX`, not an inline
# `UNIQUE` column constraint: only a plain index (not one already owned by
# a constraint) can later be adopted by "PRIMARY KEY USING INDEX" in the
# next migration without a full rebuild - and, importantly, without
# disturbing the FK constraints that repoint onto `id` in between (an
# index promoted this way keeps its identity, so a live dependent FK
# survives the promotion untouched; a named UNIQUE constraint would have
# to be dropped and re-added, which a dependent FK blocks).
from django.db import migrations, models


def add_id_columns(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "ALTER TABLE geomatics_region ADD COLUMN id bigint "
            "GENERATED BY DEFAULT AS IDENTITY"
        )
        cursor.execute(
            "CREATE UNIQUE INDEX geomatics_region_id_key ON geomatics_region (id)"
        )
        cursor.execute(
            "ALTER TABLE geomatics_department ADD COLUMN id bigint "
            "GENERATED BY DEFAULT AS IDENTITY"
        )
        cursor.execute(
            "CREATE UNIQUE INDEX geomatics_department_id_key ON geomatics_department (id)"
        )


def remove_id_columns(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE geomatics_department DROP COLUMN id")
        cursor.execute("ALTER TABLE geomatics_region DROP COLUMN id")


class Migration(migrations.Migration):
    dependencies = [
        ("geomatics", "0007_seed_france_country"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_id_columns, remove_id_columns),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="region",
                    name="id",
                    field=models.BigIntegerField(unique=True, null=True),
                ),
                migrations.AddField(
                    model_name="department",
                    name="id",
                    field=models.BigIntegerField(unique=True, null=True),
                ),
            ],
        ),
    ]
