# Generated by Django 5.1.14 on 2025-12-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("crm", "0004_note_sticky"),
        ("crm", "0005_alter_note_unique_together"),
        ("crm", "0006_alter_note_title"),
    ]

    dependencies = [
        ("crm", "0003_auto_20220802_1048"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="sticky",
            field=models.BooleanField(default=False, verbose_name="Épingler"),
        ),
        migrations.AlterUniqueTogether(
            name="note",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Titre de la note"
            ),
        ),
    ]
