# Generated by Django 5.1.14 on 2025-12-03 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0013_auto_20210720_1232"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="emails",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="note",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Plus le chiffre est élevé, plus la recommandation s'affichera en haut.",
                verbose_name="Priorité",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="accepted",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
