# Generated by Django 5.1.14 on 2025-12-03 10:28

import recoco.apps.projects.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("projects", "0021_task_refused"),
        ("projects", "0022_project_ro_key"),
        ("projects", "0023_alter_project_ro_key"),
        ("projects", "0024_alter_project_ro_key"),
        ("projects", "0025_rename_accepted_task_visited"),
    ]

    dependencies = [
        ("projects", "0020_task_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="refused",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="ro_key",
            field=models.CharField(
                default=recoco.apps.projects.utils.generate_ro_key,
                editable=False,
                max_length=32,
                unique=True,
                verbose_name="Clé d'accès lecture seule",
            ),
        ),
        migrations.RenameField(
            model_name="task",
            old_name="accepted",
            new_name="visited",
        ),
    ]
