# Generated by Django 5.1.14 on 2025-12-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0043_auto_20220131_1710"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "proposé"),
                    (1, "en cours"),
                    (2, "blocage"),
                    (3, "terminé"),
                    (4, "pas intéressé·e"),
                    (5, "déjà fait"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="taskfollowup",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "proposé"),
                    (1, "en cours"),
                    (2, "blocage"),
                    (3, "terminé"),
                    (4, "pas intéressé·e"),
                    (5, "déjà fait"),
                ]
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="muted",
            field=models.BooleanField(
                default=False, verbose_name="Ne pas envoyer de notifications"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.PositiveIntegerField(
                blank=True,
                default=1000,
                help_text="Plus le chiffre est élevé, plus la recommandation s'affichera en haut.",
                verbose_name="Priorité",
            ),
        ),
    ]
