# Generated by Django 5.1.14 on 2025-12-03 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("projects", "0069_auto_20221128_1606"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "document", "verbose_name_plural": "documents"},
        ),
        migrations.AddField(
            model_name="document",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="projects_do_content_54aa52_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("the_file__exact", ""), ("the_link__isnull", True)),
                    _negated=True,
                ),
                name="not_both_link_and_file_are_null",
            ),
        ),
    ]
