# Generated by Django 5.1.14 on 2025-12-03 10:35

import django.db.models.manager
import recoco.apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("projects", "0086_alter_note_managers"),
        ("projects", "0087_alter_project_options"),
        ("projects", "0088_alter_project_options"),
        ("projects", "0089_auto_20230522_1137"),
    ]

    dependencies = [
        ("projects", "0085_add_on_site_to_notes"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="note",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", recoco.apps.projects.models.NoteOnSiteManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "permissions": (
                    ("change_topics", "Can change the topics"),
                    ("use_advisor_note", "Can change the advisor note"),
                    ("use_private_notes", "Can use the private notes (internal)"),
                    ("use_public_notes", "Can use the public notes (conversations)"),
                    ("view_public_notes", "Can read the public notes (conversations)"),
                    ("view_private_notes", "Can read the private notes (internal)"),
                    ("view_surveys", "Can view the survey results"),
                    ("use_surveys", "Can use the surveys"),
                    ("view_tasks", "Can view and list tasks"),
                    ("view_draft_tasks", "Can view and list draft tasks"),
                    ("use_tasks", "Can use tasks"),
                    ("manage_tasks", "Can manage tasks"),
                    ("manage_documents", "Can manage the documents"),
                    ("invite_collaborators", "Can invite collaborators"),
                    ("invite_advisors", "Can invite advisors"),
                    ("manage_collaborators", "Can manage collaborators"),
                    ("manage_advisors", "Can manage advisors"),
                ),
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
        migrations.AlterModelManagers(
            name="project",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", recoco.apps.projects.models.ActiveProjectOnSiteManager()),
                (
                    "deleted_on_site",
                    recoco.apps.projects.models.DeletedProjectOnSiteManager(),
                ),
                ("all_on_site", recoco.apps.projects.models.ProjectOnSiteManager()),
            ],
        ),
        migrations.AlterField(
            model_name="project",
            name="exclude_stats",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="muted",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name="Ne pas envoyer de notifications",
            ),
        ),
    ]
