# Generated by Django 3.2.23 on 2023-12-07 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0093_add_location_xy"),
        ("projects", "0093_project_last_members_activity_at"),
    ]

    operations = []
