# Generated by Django 5.0.6 on 2024-06-04 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0096_alter_note_site"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TO_MODERATE", "En attente de modération"),
                            ("ACCEPTED", "Accepté"),
                            ("REFUSED", "Refusé"),
                        ],
                        default="TO_MODERATE",
                        max_length=20,
                    ),
                ),
                ("origin", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="project_sites",
            field=models.ManyToManyField(
                related_name="project_sites",
                through="projects.ProjectSite",
                to="sites.site",
            ),
        ),
    ]
