# Generated by Django 5.0.6 on 2024-06-06 08:41

from django.db import migrations


def populate_multisite_m2m(apps, schema_editor):
    Project = apps.get_model("projects", "Project")

    for p in Project.objects.all():
        for s in p.sites.all():
            p.projectsite_set.create(site=s, status=p.status)

        first_site = p.projectsite_set.first()
        if first_site:
            first_site.origin = True
            first_site.save()


def repopulate_sites_m2m(apps, schema_editor):
    Project = apps.get_model("projects", "Project")

    for p in Project.objects.all():
        for ps in p.projectsite_set.all():
            p.sites.add(ps.site)


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0097_projectsite_project_project_sites"),
    ]

    operations = [
        migrations.RunPython(populate_multisite_m2m, repopulate_sites_m2m),
    ]
