# Generated by Django 5.0.6 on 2024-06-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0098_site_to_msite"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectsite",
            unique_together={("project", "origin")},
        ),
    ]
