# Generated by Django 5.0.6 on 2024-06-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0099_alter_projectsite_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="sites",
        ),
    ]
