# Generated by Django 5.0.6 on 2024-06-18 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0099_alter_projectsite_and_more"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="projectsite",
            name="unique_origin_site",
        ),
        migrations.AlterField(
            model_name="projectsite",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectsite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_origin", True)),
                fields=("project", "is_origin"),
                name="unique_origin_site",
            ),
        ),
    ]
