# Generated by Django 5.0.6 on 2024-06-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0100_remove_project_sites"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="project_sites",
            new_name="sites",
        ),
    ]
