# Generated by Django 5.0.6 on 2024-06-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0101_rename_project_sites_project_sites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="status",
        ),
        migrations.AlterField(
            model_name="projectsite",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("TO_MODERATE", "En attente de modération"),
                    ("READY", "En attente"),
                    ("IN_PROGRESS", "En cours"),
                    ("DONE", "Traité"),
                    ("STUCK", "Conseil Interrompu"),
                    ("REFUSED", "Refusé"),
                ],
                default="TO_MODERATE",
                max_length=20,
            ),
        ),
    ]
