# Generated by Django 4.2.13 on 2024-07-23 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0101_projectsite_unique_site_per_project"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="projectswitchtender",
            managers=[],
        ),
        migrations.AlterField(
            model_name="projectswitchtender",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="switchtender_sites",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="projectswitchtender",
            name="switchtender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects_switchtended_per_site",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
