# Generated by Django 5.0.6 on 2024-06-17 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0102_remove_project_status_alter_projectsite_status"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectsite",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="projectsite",
            name="site",
            field=models.ForeignKey(
                limit_choices_to={"is_staff": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.site",
            ),
        ),
        migrations.AlterField(
            model_name="projectsite",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("TO_PROCESS", "A traiter"),
                    ("READY", "En attente"),
                    ("IN_PROGRESS", "En cours"),
                    ("DONE", "Traité"),
                    ("STUCK", "Conseil Interrompu"),
                    ("REJECTED", "Refusé"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="projectsite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("origin", True)),
                fields=("project", "site", "origin"),
                name="unique_origin_site",
            ),
        ),
    ]
