# Generated by Django 4.2.14 on 2024-10-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0103_alter_project_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="survey_answers",
            field=models.JSONField(default=dict),
        ),
    ]
