# Generated by Django 4.2.11 on 2025-01-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0104_projectsite_sent_by_projectsite_sent_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_diagnostic_done",
            field=models.BooleanField(
                default=False, verbose_name="Appel de diagnostic réalisé"
            ),
        ),
    ]
