# Generated by Django 5.1.14 on 2025-12-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0104_projectsite_sent_by_projectsite_sent_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_diagnostic_done",
            field=models.BooleanField(
                default=False, verbose_name="Appel de diagnostic réalisé"
            ),
        ),
        migrations.AlterModelManagers(
            name="userprojectstatus",
            managers=[],
        ),
    ]
