# Generated by Django 4.2.16 on 2025-01-27 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0104_projectsite_sent_by_projectsite_sent_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="projects.topic",
            ),
        ),
    ]
