# Generated by Django 4.2.16 on 2025-01-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0105_note_topic"),
        ("projects", "0105_project_is_diagnostic_done"),
    ]

    operations = []
