# Generated by Django 4.2.17 on 2025-02-10 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0105_project_is_diagnostic_done"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="userprojectstatus",
            managers=[],
        ),
    ]
