# Generated by Django 4.2.19 on 2025-03-24 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("addressbook", "0012_search_config_french_unaccent"),
        (
            "projects",
            "0105_project_is_diagnostic_done_squashed_0106_alter_userprojectstatus_managers",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="addressbook.contact",
            ),
        ),
    ]
