# Generated by Django 4.2.19 on 2025-02-20 11:05

from django.conf import settings
from django.db import migrations
from django.db.models import Count, Q


def deduplicate_ups(apps, schema_editor):
    UserProjectStatus = apps.get_model("projects", "UserProjectStatus")  # noqa
    Project = apps.get_model("projects", "Project")
    User = apps.get_model("auth", "User")
    db_alias = schema_editor.connection.alias

    for user in User.objects.all():
        for project in (
            Project.objects.using(db_alias)
            .filter(user_project_states__user=user)
            .annotate(
                ups_count=Count(
                    "user_project_states", filter=Q(user_project_states__user=user)
                )
            )
            .filter(ups_count__gte=2)
        ):
            print("**", project)
            project_ups = project.user_project_states.filter(user=user).order_by(
                "status"
            )

            real_ups = project_ups.last()

            project_ups.delete()

            real_ups.save()

            best = "NEW"  # noqa FIXME: wip
            for ups in project_ups:
                print("=> ", ups.project, ups.site.name, ups.status)

            raise


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0107_merge_20250220_1205"),
    ]

    operations = [
        migrations.RunPython(deduplicate_ups),
        migrations.AlterUniqueTogether(
            name="userprojectstatus",
            unique_together={("user", "project")},
        ),
        migrations.RemoveField(
            model_name="userprojectstatus",
            name="site",
        ),
    ]
