# Generated by Django 4.2.19 on 2025-03-20 15:14
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0108_note_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="inactive_reason",
            field=models.CharField(
                blank=True,
                default="",
                max_length=256,
                null=True,
                verbose_name="Raison de l'inactivité du dossier",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="inactive_since",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Quand le dossier a été déclaré inactif",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Nom du dossier"),
        ),
    ]
