# Generated by Django 4.2.19 on 2025-05-06 08:47

from django.db import migrations


def delete_perm_site_use_project_tags(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    site_ct = ContentType.objects.get(app_label="sites", model="site")

    queryset = Permission.objects.filter(
        codename="use_project_tags",
        content_type=site_ct,
    )
    if queryset.exists():
        queryset.delete()


def undo_delete_perm_site_use_project_tags(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    site_ct = ContentType.objects.get(app_label="sites", model="site")

    Permission.objects.get_or_create(
        codename="use_project_tags",
        name="Can use tags on projects",
        content_type=site_ct,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0110_alter_project_options"),
    ]

    operations = [
        migrations.RunPython(
            delete_perm_site_use_project_tags,
            undo_delete_perm_site_use_project_tags,
        ),
    ]
