# Generated by Django 5.1.14 on 2025-12-03 10:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0112_projectcreationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcreationrequest",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="project",
            name="last_manual_reactivation",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Quand le dossier a été manuellement réactivé",
            ),
        ),
    ]
