# Generated by Django 5.1.11 on 2025-08-20 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0112_projectcreationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcreationrequest",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
