# Generated by Django 5.1.13 on 2025-10-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0113_projectcreationrequest_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_manual_reactivation",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Quand le dossier a été manuellement réactivé",
            ),
        ),
    ]
