# Generated by Django 5.1.15 on 2025-12-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0115_alter_document_the_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsite",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRE_DRAFT", "Incomplet"),
                    ("DRAFT", "Brouillon"),
                    ("TO_PROCESS", "A traiter"),
                    ("READY", "En attente"),
                    ("IN_PROGRESS", "En cours"),
                    ("DONE", "Traité"),
                    ("STUCK", "Conseil Interrompu"),
                    ("REJECTED", "Refusé"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
