# Generated by Django 5.1.15 on 2026-03-13 17:04

import django.core.validators
import recoco.apps.projects.models
import recoco.apps.projects.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0116_alter_projectsite_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="the_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=recoco.apps.projects.models.Document.upload_path,
                validators=[
                    recoco.apps.projects.validators.MimetypeValidator(
                        allows=[
                            "text/plain",
                            "image/png",
                            "image/jpg",
                            "image/gif",
                            "image/jpeg",
                            "image/pjpeg",
                            "application/pdf",
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "application/vnd.oasis.opendocument.text",
                            "application/vnd.ms-excel",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                            "application/vnd.oasis.opendocument.spreadsheet",
                            "application/vnd.ms-powerpoint",
                            "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                            "application/vnd.oasis.opendocument.presentation",
                            "application/x-zip-compressed",
                            "application/zip",
                        ]
                    ),
                    django.core.validators.FileExtensionValidator(
                        [
                            "txt",
                            "md",
                            "png",
                            "jpg",
                            "jpeg",
                            "pdf",
                            "doc",
                            "docx",
                            "odt",
                            "xls",
                            "xlsx",
                            "odc",
                            "ppt",
                            "pptx",
                            "odp",
                            "zip",
                        ]
                    ),
                ],
            ),
        ),
    ]
