# Generated by Django 5.1.15 on 2026-03-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0117_alter_document_the_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="private",
            field=models.BooleanField(default=False),
        ),  # history documnts are public
        migrations.AlterModelOptions(
            name="project",
            options={
                "permissions": (
                    ("change_topics", "Can change the topics"),
                    ("use_advisor_note", "Can change the advisor note"),
                    ("use_private_notes", "Can use the private notes (internal)"),
                    ("use_public_notes", "Can use the public notes (conversations)"),
                    ("view_public_notes", "Can read the public notes (conversations)"),
                    ("view_private_notes", "Can read the private notes (internal)"),
                    ("view_surveys", "Can view the survey results"),
                    ("use_surveys", "Can use the surveys"),
                    ("view_tasks", "Can view and list tasks"),
                    ("view_draft_tasks", "Can view and list draft tasks"),
                    ("use_tasks", "Can use tasks"),
                    ("manage_tasks", "Can manage tasks"),
                    ("manage_documents", "Can manage the documents"),
                    (
                        "manage_private_documents",
                        "Can manage advisor space documents",
                    ),  # this line is the addition
                    ("invite_collaborators", "Can invite collaborators"),
                    ("invite_advisors", "Can invite advisors"),
                    ("manage_collaborators", "Can manage collaborators"),
                    ("manage_advisors", "Can manage advisors"),
                    ("change_location", "Can change the geolocation"),
                    ("use_project_tags", "Can use tags on projects"),
                ),
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
        migrations.AlterField(
            model_name="document",
            name="private",
            field=models.BooleanField(default=True),
        ),  # but default should be private from now on
    ]
