# Generated by Django 5.2.13 on 2026-04-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0118_document_private"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="sites",
            field=models.ManyToManyField(
                related_name="project_sites",
                through="projects.ProjectSite",
                through_fields=("project", "site"),
                to="sites.site",
            ),
        ),
    ]
