# Generated by Django 5.2.16 on 2026-08-18 14:04

from django.db import migrations
from django.db.models import CharField
from django.db.models.expressions import Subquery, OuterRef, F
from django.db.models.fields import IntegerField
from django.db.models.functions import Cast

from recoco import verbs


def fill_set_inactive_by(apps, schema_editor):
    Action = apps.get_model("actstream", "Action")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Project = apps.get_model("projects", "Project")
    project_ct = ContentType.objects.get_for_model(Project)
    verbs_inactive = [verbs.Project.SET_INACTIVE, "a mis en pause le projet"]

    missing_set_inactive_by = Project.objects.filter(
        inactive_since__isnull=False, set_inactive_by__isnull=True
    ).exclude(
        inactive_reason="Pas de connexion de membres de la collectivité dans les 12 mois"
    )

    last_inactivater_sq = Subquery(
        Action._base_manager.filter(  # _base_manager to have no filtering
            verb__in=verbs_inactive,
            action_object_content_type_id=project_ct.id,
            action_object_object_id=Cast(OuterRef("pk"), output_field=CharField()),
        )
        .order_by("-timestamp")
        .values_list("actor_object_id")[:1]
    )
    annotated = missing_set_inactive_by.annotate(last_inactivater=last_inactivater_sq)

    # projects for which we can id the inactivater
    annotated.filter(last_inactivater__isnull=False).update(
        set_inactive_by_id=Cast(F("last_inactivater"), output_field=IntegerField())
    )

    # alert about other projects
    rest = annotated.filter(last_inactivater__isnull=False)
    if not rest.exists():
        return
    print(f"{rest.count()} projects still don't have set_inactive_by set :")
    for project in rest.values("id", "name", "inactive_since"):
        print(project)


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0120_project_set_inactive"),
        ("actstream", "0004_add_multisite_support"),
    ]

    operations = [
        migrations.RunPython(
            fill_set_inactive_by,
            migrations.RunPython.noop,
        )
    ]
