# Generated by Django 5.2.17 on 2026-08-21 09:26

import django.db.models.manager
import recoco.apps.projects.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0121_fill_set_inactive_by_history"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "base_manager_name": "all",
                "permissions": (
                    ("change_topics", "Can change the topics"),
                    ("use_advisor_note", "Can change the advisor note"),
                    ("use_private_notes", "Can use the private notes (internal)"),
                    ("use_public_notes", "Can use the public notes (conversations)"),
                    ("view_public_notes", "Can read the public notes (conversations)"),
                    ("view_private_notes", "Can read the private notes (internal)"),
                    ("view_surveys", "Can view the survey results"),
                    ("use_surveys", "Can use the surveys"),
                    ("view_tasks", "Can view and list tasks"),
                    ("view_draft_tasks", "Can view and list draft tasks"),
                    ("use_tasks", "Can use tasks"),
                    ("manage_tasks", "Can manage tasks"),
                    ("manage_documents", "Can manage the documents"),
                    ("manage_private_documents", "Can manage advisor space documents"),
                    ("invite_collaborators", "Can invite collaborators"),
                    ("invite_advisors", "Can invite advisors"),
                    ("manage_collaborators", "Can manage collaborators"),
                    ("manage_advisors", "Can manage advisors"),
                    ("change_location", "Can change the geolocation"),
                    ("use_project_tags", "Can use tags on projects"),
                ),
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
        migrations.AlterModelManagers(
            name="project",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", recoco.apps.projects.models.ActiveProjectOnSiteManager()),
                (
                    "deleted_on_site",
                    recoco.apps.projects.models.DeletedProjectOnSiteManager(),
                ),
                ("all", django.db.models.manager.Manager()),
                ("all_on_site", recoco.apps.projects.models.ProjectOnSiteManager()),
            ],
        ),
    ]
