# Generated by Django 5.1.14 on 2025-12-03 10:28

import django.db.models.deletion
import dynamic_forms.models
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("onboarding", "0001_initial"),
        ("onboarding", "0002_onboardingresponse"),
        ("onboarding", "0003_alter_onboardingresponse_onboarding"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Onboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form", dynamic_forms.models.FormField()),
            ],
        ),
        migrations.CreateModel(
            name="OnboardingResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", dynamic_forms.models.ResponseField()),
                (
                    "onboarding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="onboarding.onboarding",
                    ),
                ),
            ],
        ),
    ]
