# Generated by Django 5.1.11 on 2025-08-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="position",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
