# Generated by Django 5.1.11 on 2025-08-29 12:37

from django.db import migrations, transaction

from guardian.utils import get_anonymous_user


def copy_public_notes_to_messages(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Note = apps.get_model("projects", "Note")
    Message = apps.get_model("conversations", "Message")
    MarkdownNode = apps.get_model("conversations", "MarkdownNode")

    anonymous_user = get_anonymous_user()

    for project in Project.objects.all():
        for note in Note.objects.filter(project=project, public=True):
            with transaction.atomic():
                msg = Message.objects.create(
                    project=project,
                    posted_by_id=note.created_by_id or anonymous_user.pk,
                    created=note.created_on,
                    modified=note.updated_on,
                )
                MarkdownNode.objects.create(message=msg, position=1, text=note.content)


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_node_position"),
    ]

    operations = [migrations.RunPython(copy_public_notes_to_messages, lambda x: x)]
