# Generated by Django 5.1.11 on 2025-08-29 12:37

from django.contrib.contenttypes.models import ContentType
from django.db import migrations, transaction
from guardian.utils import get_anonymous_user


def copy_public_notes_to_messages(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Note = apps.get_model("projects", "Note")
    Document = apps.get_model("projects", "Document")
    Message = apps.get_model("conversations", "Message")
    MarkdownNode = apps.get_model("conversations", "MarkdownNode")
    ContactNode = apps.get_model("conversations", "ContactNode")
    DocumentNode = apps.get_model("conversations", "DocumentNode")

    anonymous_user = get_anonymous_user()

    for project in Project.objects.all():
        for note in Note.objects.filter(project=project, public=True):
            with transaction.atomic():
                msg = Message.objects.create(
                    project=project,
                    posted_by_id=note.created_by_id or anonymous_user.pk,
                    created=note.created_on,
                    modified=note.updated_on,
                )
                prev_node = MarkdownNode.objects.create(
                    message=msg, position=1, text=note.content
                )

                if note.contact:
                    prev_node = ContactNode.objects.create(
                        message=msg,
                        position=prev_node.position + 1,
                        contact=note.contact,
                    )

                if document := Document.objects.filter(
                    content_type_id=ContentType.objects.get_for_model(Note).pk,
                    object_id=note.pk,
                ).first():
                    prev_node = DocumentNode.objects.create(
                        message=msg, position=prev_node.position + 1, document=document
                    )


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_node_position"),
    ]

    operations = [
        migrations.RunPython(copy_public_notes_to_messages, lambda x, y: None)
    ]
