# Generated by Django 5.1.12 on 2025-09-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_public_note_to_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="deleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
