# Generated by Django 5.1.11 on 2025-08-29 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0003_public_note_to_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="in_reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="conversations.message",
            ),
        ),
    ]
