# Generated by Django 5.1.11 on 2025-09-08 13:34

from django.db import migrations


def forwards_func(apps, schema_editor):
    RecommendationNode = apps.get_model("conversations", "RecommendationNode")
    MarkdownNode = apps.get_model("conversations", "MarkdownNode")
    ContactNode = apps.get_model("conversations", "ContactNode")
    DocumentNode = apps.get_model("conversations", "DocumentNode")

    ContentType = apps.get_model("contenttypes", "ContentType")

    for Model in [RecommendationNode, MarkdownNode, ContactNode, DocumentNode]:
        new_ct = ContentType.objects.get_for_model(Model)
        Model.objects.filter(polymorphic_ctype__isnull=True).update(
            polymorphic_ctype=new_ct
        )


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0003_reco_to_messages"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
