# Generated by Django 5.1.11 on 2025-08-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0004_message_in_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationnode",
            name="text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
