# Generated by Django 5.1.13 on 2025-10-28 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0005_message_deleted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="node",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="node",
            unique_together={("position", "message")},
        ),
    ]
