# Generated by Django 5.1.15 on 2025-12-30 16:07

from django.db import migrations
from django.utils import timezone
from tqdm import tqdm

from recoco import verbs
from recoco.apps.conversations.models import Message
from recoco.apps.conversations.utils import gather_annotations_for_message_notification


def convert_public_note_notifications(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Note = apps.get_model("projects", "Note")
    User = apps.get_model("auth", "User")
    Project = apps.get_model("projects", "Project")
    public_note_verb = "a envoyé un message dans l'espace conversation"
    content_type = ContentType.objects.get_for_model(Note)
    for notif in tqdm(
        Notification.objects.filter(
            verb=public_note_verb,
            unread=True,
            action_object_content_type_id=content_type.id,
        )
    ):
        note = Note.objects.get(pk=notif.action_object_object_id)

        # inactive or muted project: we just mark the notification as read ond forget about it
        if note.project.inactive_since is not None or note.project.muted:
            notif.unread = False
            notif.save()
            continue

        # ignore private notes as they are not concerned
        if not note.public:
            continue

        try:
            # get corresponding message to create its own notification
            message = Message.objects.get(
                created=note.created_on,
                modified=note.updated_on,
                project_id=note.project.pk,
            )

            Notification(
                recipient=notif.recipient,
                actor_content_type=ContentType.objects.get_for_model(User),
                actor_object_id=notif.actor_object_id,
                target_object_id=notif.target_object_id,
                target_content_type=ContentType.objects.get_for_model(Project),
                action_object_object_id=message.id,
                action_object_content_type=ContentType.objects.get_for_model(Message),
                verb=verbs.Conversation.POST_MESSAGE,
                public=True,
                description=None,
                data={
                    "annotations": gather_annotations_for_message_notification(message)
                },
                emailed=notif.emailed,
                timestamp=timezone.now(),
                level="info",
                site_id=notif.site_id,
            )

            # notify.send(recipient=notif.recipient, site_id=notif.site.id, **notification)
        except Message.DoesNotExist:
            print(f"no message found for {note}. skipped")
        except User.DoesNotExist:
            print(f"sender not found for {note}. skipped")


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0006_alter_node_options_alter_node_unique_together"),
        (
            "notifications",
            "0012_rename_notification_recipient_unread_notificatio_recipie_8bedf2_idx",
        ),
        ("projects", "0116_alter_projectsite_status"),
    ]

    operations = [
        migrations.RunPython(convert_public_note_notifications, lambda x, y: None)
    ]
