# Generated by Django 3.2.18 on 2023-06-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0002_auto_20221104_1343"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="acquired",
        ),
        migrations.AlterField(
            model_name="challenge",
            name="acquired_on",
            field=models.DateTimeField(default=None, verbose_name="Date d'acquisition"),
        ),
    ]
