# Generated by Django 3.2.19 on 2023-06-20 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("training", "0004_alter_challenge_acquired_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengedefinition",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="challenge",
            unique_together={("challenge_definition", "user")},
        ),
    ]
