# Generated by Django 5.1.14 on 2025-12-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0007_auto_20230620_1815"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengedefinition",
            name="week_inactivity_repeat",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="challenge",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="challenge",
            name="snoozed_on",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Date de report"
            ),
        ),
    ]
