# Generated by Django 3.2.23 on 2024-02-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0009_alter_challenge_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="snoozed_on",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Date de report"
            ),
        ),
    ]
