# Generated by Django 5.1.14 on 2025-11-24 16:34

import django.db.models.deletion
import django.db.models.manager
import recoco.apps.training.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        (
            "training",
            "0008_challengedefinition_week_inactivity_repeat_squashed_0010_challenge_snoozed_on",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="challengedefinition",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                (
                    "on_site",
                    recoco.apps.training.models.ChallengeDefinitionOnSiteManager(),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="challengedefinition",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.site",
            ),
        ),
    ]
