# Generated by Django 3.2.13 on 2022-07-20 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("addressbook", "0004_alter_contact_division"),
        ("home", "0004_userprofile_organization_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registered_profiles",
                to="addressbook.organization",
            ),
        ),
    ]
