# Generated by Django 3.2.13 on 2022-07-26 12:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_userprofile_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_no",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
    ]
