# Generated by Django 3.2.13 on 2022-06-06 11:59

import django.db.models.deletion
from django.db import migrations, models
from urbanvitaliz.apps.onboarding import models as onboarding_models
import json


def create_default_onboarding(apps, schema_editor):
    form = [
        {
            "type": "text",
            "required": False,
            "label": "Vide",
            "className": "form-control",
            "name": "text-0000000000000-0",
            "subtype": "text",
        }
    ]

    try:
        onboarding_models.Onboarding.objects.get(pk=1)
    except onboarding_models.Onboarding.DoesNotExist:
        onboarding_models.Onboarding.objects.create(form=json.dumps(form))


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0003_alter_onboardingresponse_onboarding"),
        ("home", "0006_alter_siteconfiguration_site"),
    ]

    operations = [
        migrations.RunPython(create_default_onboarding, lambda x, y: None),
        migrations.AddField(
            model_name="siteconfiguration",
            name="onboarding",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="onboarding.onboarding",
            ),
            preserve_default=False,
        ),
    ]
