# Generated by Django 3.2.14 on 2022-08-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_userprofile_phone_no"),
        ("home", "0007_siteconfiguration_onboarding"),
    ]

    operations = []
