# Generated by Django 3.2.15 on 2022-09-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_merge_20220801_1202"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="sender_email",
            field=models.EmailField(default="noreply@recoconseil.fr", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="sender_name",
            field=models.CharField(default="Recoconseil", max_length=30),
            preserve_default=False,
        ),
    ]
