# Generated by Django 3.2.15 on 2022-09-13 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("home", "0009_auto_20220913_1424"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configuration",
                to="sites.site",
            ),
        ),
    ]
