# Generated by Django 3.2.15 on 2022-09-23 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
        ('home', '0010_alter_siteconfiguration_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserObjectPermissionOnSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(max_length=255, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupObjectPermissionOnSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(max_length=255, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='userobjectpermissiononsite',
            index=models.Index(fields=['content_type', 'object_pk'], name='home_userob_content_e8917d_idx'),
        ),
        migrations.AddIndex(
            model_name='userobjectpermissiononsite',
            index=models.Index(fields=['content_type', 'object_pk', 'user', 'site'], name='home_userob_content_b39e6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userobjectpermissiononsite',
            unique_together={('user', 'permission', 'object_pk')},
        ),
        migrations.AddIndex(
            model_name='groupobjectpermissiononsite',
            index=models.Index(fields=['content_type', 'object_pk'], name='home_groupo_content_437f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='groupobjectpermissiononsite',
            index=models.Index(fields=['content_type', 'object_pk', 'group', 'site'], name='home_groupo_content_2b8b77_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupobjectpermissiononsite',
            unique_together={('group', 'permission', 'object_pk')},
        ),
    ]
