# Generated by Django 3.2.15 on 2022-09-23 13:51

from django.db import migrations
import urbanvitaliz.apps.home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220923_1131'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='groupobjectpermissiononsite',
            managers=[
                ('objects', urbanvitaliz.apps.home.models.GroupObjectPermissionManagerOnSite()),
            ],
        ),
        migrations.AlterModelManagers(
            name='userobjectpermissiononsite',
            managers=[
                ('objects', urbanvitaliz.apps.home.models.UserObjectPermissionManagerOnSite()),
            ],
        ),
    ]
