# Generated by Django 3.2.16 on 2023-02-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20230117_1050'),
        ('home', '0013_auto_20220923_1557'),
    ]

    operations = [
    ]
