# Generated by Django 3.2.16 on 2023-02-20 12:29

from django.db import migrations
from django.contrib.auth import models as auth_models
from urbanvitaliz.apps.home.utils import make_group_name_for_site

from .. import models


def upgrade_site_groups(apps, schema_editor):
    Site = apps.get_model("sites", "Site")

    for site in Site.objects.all():
        for name, permissions in models.SITE_GROUP_PERMISSIONS.items():
            group_name = make_group_name_for_site(name, site)
            auth_models.Group.objects.get_or_create(name=group_name)

    group_transitions = (
        ("example_com_advisor", "advisor"),
        ("example_com_staff", "staff"),
    )

    for oldname, newname in group_transitions:
        for user in auth_models.User.objects.filter(groups__name=oldname):
            for site in user.profile.sites.all():
                group_name = make_group_name_for_site(newname, site)
                group = auth_models.Group.objects.get(name=group_name)
                group.user_set.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_merge_0011_auto_20230117_1050_0013_auto_20220923_1557"),
    ]

    operations = [migrations.RunPython(upgrade_site_groups, lambda x, y: None)]
