# Generated by Django 3.2.17 on 2023-02-20 16:57

from django.db import migrations

from django.contrib.auth import models


def remove_unused_groups(apps, schema_editor):
    groups = ["switchtender", "project_moderator"]
    models.Group.objects.filter(name__in=groups).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_create_site_groups_and_permissions_20230220_1329"),
    ]

    operations = [
        migrations.RunPython(remove_unused_groups, lambda x, y: None),
    ]
