# Generated by Django 3.2.18 on 2023-07-16 12:06

from django.db import migrations

from urbanvitaliz.utils import RunSQLFile
from pathlib import Path
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_remove_unused_groups"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        RunSQLFile(sql_file_path=Path(settings.BASE_DIR / "sql/update-verbs.sql"))
    ]
