# Generated by Django 3.2.18 on 2023-07-16 12:06

from django.db import migrations

from urbanvitaliz.utils import RunSQLFile
from pathlib import Path


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_remove_unused_groups"),
    ]

    operations = [RunSQLFile(sql_file_path=Path("sql/update-verbs.sql"))]
