# Generated by Django 3.2.18 on 2023-11-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_update_verbs"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="reminder_interval",
            field=models.IntegerField(default=42, verbose_name="Interval des rappels"),
        ),
    ]
