# Generated by Django 3.2.23 on 2024-02-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_userprofile_previous_login_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="contact_form_recipient",
            field=models.EmailField(
                default="noreply@nodomain.nowhere",
                help_text="Adresse d'expédition pour le formulaire de contact",
                max_length=254,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="sender_email",
            field=models.EmailField(
                help_text="Adresse de l'expéditeur pour les emails automatiques",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="sender_name",
            field=models.CharField(
                help_text="Nom de l'expéditeur pour les emails automatiques",
                max_length=30,
            ),
        ),
    ]
