# Generated by Django 4.2.13 on 2024-07-04 13:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geomatics", "0004_alter_department_region"),
        ("projects", "0096_alter_note_site"),
        ("tasks", "0004_alter_task_topic"),
        ("resources", "0029_remove_resource_old_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="DSResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("schema", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("DETR_DSIL", "DETR DSIL")],
                        default="DETR_DSIL",
                        max_length=50,
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="demarches_simplifiees",
                        to="geomatics.department",
                        verbose_name="Départements concernés",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resources.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Démarche simplifiée",
                "verbose_name_plural": "Démarches simplifiées",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DSFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("dossier_id", models.CharField(max_length=255)),
                ("dossier_url", models.URLField()),
                ("dossier_number", models.IntegerField()),
                ("dossier_prefill_token", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("content", models.JSONField()),
                ("content_hash", models.CharField(max_length=255)),
                (
                    "ds_resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demarches_simplifiees.dsresource",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ds_folder",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier pré-rempli",
                "verbose_name_plural": "Dossiers pré-remplis",
                "ordering": ["-created"],
                "unique_together": {("project", "ds_resource")},
            },
        ),
    ]
