# Generated by Django 4.2.13 on 2024-07-01 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resources", "0029_remove_resource_old_tags"),
        ("tasks", "0003_alter_task_options"),
        ("projects", "0096_alter_note_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="DSResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("schema", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resources.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Démarche simplifiée",
                "verbose_name_plural": "Démarches simplifiées",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DSFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("dossier_id", models.CharField(max_length=255)),
                ("dossier_url", models.URLField()),
                ("dossier_number", models.IntegerField()),
                ("content", models.JSONField()),
                ("content_hash", models.CharField(max_length=255)),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tasks.task",
                    ),
                ),
                (
                    "ds_resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demarches_simplifiees.dsresource",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier de Démarches Simplifiées",
                "verbose_name_plural": "Dossiers de Démarches Simplifiées",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["project", "ds_resource", "content_hash"],
                        name="demarches_s_project_11f721_idx",
                    )
                ],
            },
        ),
    ]
