# Generated by Django 4.2.13 on 2024-07-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demarches_simplifiees", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dsfolder",
            options={
                "ordering": ["-created"],
                "verbose_name": "Dossier pré-rempli",
                "verbose_name_plural": "Dossiers pré-remplis",
            },
        ),
        migrations.AddField(
            model_name="dsfolder",
            name="dossier_prefill_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dsfolder",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
