# Generated by Django 4.2.14 on 2024-09-03 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demarches_simplifiees", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dsresource",
            name="type",
        ),
    ]
