# Generated by Django 4.2.14 on 2024-10-01 09:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("demarches_simplifiees", "0002_remove_dsresource_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DSMappingField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("field_id", models.CharField(max_length=255)),
                ("field_label", models.CharField(max_length=255)),
                ("field_options", models.JSONField(default=list)),
                (
                    "project_lookup_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "ds_resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapping_fields",
                        to="demarches_simplifiees.dsresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapping de champ",
                "verbose_name_plural": "Mappings de champ",
                "ordering": ["field_label"],
                "unique_together": {("ds_resource", "field_id")},
            },
        ),
    ]
