# Generated by Django 4.2.13 on 2024-07-02 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geomatics", "0004_alter_department_region"),
        ("demarches_simplifiees", "0002_alter_dsfolder_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsresource",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geomatics.department",
            ),
        ),
        migrations.AddField(
            model_name="dsresource",
            name="field_mapping",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="dsresource",
            name="type",
            field=models.CharField(
                choices=[("DETR_DSIL", "DETR DSIL")], default="DETR_DSIL", max_length=50
            ),
        ),
    ]
