# Generated by Django 4.2.16 on 2024-12-03 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("demarches_simplifiees", "0002_remove_dsresource_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DSMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("fields_mapping", models.JSONField(blank=True, default=dict)),
                (
                    "ds_resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demarches_simplifiees.dsresource",
                    ),
                ),
                ("sites", models.ManyToManyField(blank=True, to="sites.site")),
            ],
            options={
                "verbose_name": "Mapping Démarche simplifiée",
                "verbose_name_plural": "Mappings Démarches simplifiées",
                "ordering": ["-created"],
            },
        ),
    ]
