# Generated by Django 4.2.19 on 2025-03-31 08:42

from django.db import migrations


def update_dsmapping_mappings(apps, schema_editor):
    DSMapping = apps.get_model("demarches_simplifiees", "DSMapping")

    for ds_mapping in DSMapping.objects.all():
        ds_mapping.mapping = {
            key: [{"value": value}] for key, value in ds_mapping.mapping.items()
        }
        ds_mapping.save()


def reverse_update_dsmapping_mappings(apps, schema_editor):
    DSMapping = apps.get_model("demarches_simplifiees", "DSMapping")

    for ds_mapping in DSMapping.objects.all():
        ds_mapping.mapping = {
            key: value[0]["value"] for key, value in ds_mapping.mapping.items()
        }
        ds_mapping.save()


class Migration(migrations.Migration):
    dependencies = [
        ("demarches_simplifiees", "0003_dsmapping"),
    ]

    operations = [
        migrations.RunPython(
            update_dsmapping_mappings,
            reverse_update_dsmapping_mappings,
        ),
    ]
