# Generated by Django 5.1.9 on 2025-06-04 07:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demarches_simplifiees", "0004_update_dsmapping_mappings"),
        ("tasks", "0006_taskfollowup_contact_alter_task_contact"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dsfolder",
            unique_together={("recommendation", "ds_resource")},
        ),
        migrations.RemoveField(
            model_name="dsfolder",
            name="project",
        ),
    ]
