# Generated by Django 5.1.15 on 2026-04-02 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demarches_simplifiees", "0005_alter_dsfolder_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DSFolder",
        ),
    ]
