# Generated by Django 3.2.6 on 2021-09-28 11:29

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.CharField(max_length=128)),
                ("subject", models.TextField(default="")),
                ("text", models.TextField(default="")),
                ("html", models.TextField(default="")),
                ("deadline", models.DateField()),
                ("sent", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "mail",
                "verbose_name_plural": "mails",
            },
            managers=[
                ("to_send", django.db.models.manager.Manager()),
            ],
        ),
    ]
