# Generated by Django 3.2.6 on 2021-09-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mail",
            old_name="sent",
            new_name="sent_on",
        ),
    ]
