# Generated by Django 3.2.8 on 2021-10-12 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("reminders", "0002_rename_sent_mail_sent_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="mail",
            name="content_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mail",
            name="object_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mail",
            name="origin",
            field=models.IntegerField(
                choices=[(1, "Personal"), (2, "Assigned")], default=0
            ),
        ),
    ]
