# Generated by Django 3.2.13 on 2022-06-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0003_alter_emailtemplate_name"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("reminders", "0004_auto_20220208_1410"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Mail",
            new_name="Reminder",
        ),
    ]
