# Generated by Django 3.2.13 on 2022-06-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0005_rename_mail_reminder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reminder",
            options={"verbose_name": "rappel", "verbose_name_plural": "rappels"},
        ),
        migrations.AlterModelManagers(
            name="reminder",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="html",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="template",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="template_params",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="text",
        ),
        migrations.AlterField(
            model_name="reminder",
            name="origin",
            field=models.IntegerField(
                choices=[(0, "Système"), (1, "Personal"), (2, "Assigned")], default=0
            ),
        ),
    ]
