# Generated by Django 3.2.18 on 2023-10-23 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import urbanvitaliz.apps.reminders.models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("reminders", "0007_auto_20231023_1614"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="reminder",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", urbanvitaliz.apps.reminders.models.ReminderOnSiteManager()),
                (
                    "on_site_sent",
                    urbanvitaliz.apps.reminders.models.SentReminderOnSiteManager(),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reminder",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reminder",
            name="kind",
            field=models.IntegerField(
                choices=[(0, "Nouvelle Recommandation"), (1, "Où en êtes-vous ?")],
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="origin",
            field=models.IntegerField(
                choices=[(0, "Système"), (1, "Personal"), (2, "Assigned")],
                default=0,
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="sent_on",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
