# Generated by Django 3.2.23 on 2023-12-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reminders", "0010_auto_20231023_1834"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="sent_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
