# Generated by Django 3.2.13 on 2022-05-05 07:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import urbanvitaliz.apps.invites.models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("invites", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="invite",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", urbanvitaliz.apps.invites.models.InviteOnSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name="invite",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
            preserve_default=False,
        ),
    ]
