# Generated by Django 3.2.16 on 2023-01-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invites", "0003_alter_invite_role"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invite",
            unique_together=set(),
        ),
    ]
