# Generated by Django 3.2.18 on 2023-06-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invites", "0004_alter_invite_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="role",
            field=models.CharField(
                choices=[
                    ("COLLABORATOR", "Participant·e"),
                    ("SWITCHTENDER", "Conseiller·e"),
                    ("OBSERVER", "Observateur·trice"),
                ],
                default="COLLABORATOR",
                max_length=20,
            ),
        ),
    ]
