# Generated by Django 3.2.13 on 2022-06-06 09:47

from django.db import migrations, models
import dynamic_forms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Onboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form", dynamic_forms.models.FormField()),
            ],
        ),
    ]
