# Generated by Django 3.2.13 on 2022-06-06 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0002_onboardingresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardingresponse",
            name="onboarding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="onboarding.onboarding",
            ),
        ),
    ]
