# Generated by Django 3.2.13 on 2022-05-10 08:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import recoco.apps.addressbook.models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("addressbook", "0004_alter_contact_division"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="contact",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                (
                    "on_site",
                    recoco.apps.addressbook.models.ContactOnSiteManager(),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contact",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
            preserve_default=False,
        ),
    ]
