# Generated by Django 4.2.17 on 2025-01-14 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("addressbook", "0009_alter_organization_departments"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=90, verbose_name="Nom")),
            ],
            options={
                "verbose_name": "Groupement d'organisations",
                "verbose_name_plural": "Groupements d'organisations",
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizations",
                to="addressbook.organizationgroup",
            ),
        ),
    ]
