# Generated by Django 4.2.19 on 2025-02-17 15:39

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("addressbook", "0011_contact_created_contact_modified_and_more"),
    ]

    operations = [
        UnaccentExtension(),
        migrations.RunSQL(
            sql="""
                CREATE TEXT SEARCH CONFIGURATION french_unaccent ( COPY = french );
                ALTER TEXT SEARCH CONFIGURATION french_unaccent
                ALTER MAPPING FOR hword, hword_part, word WITH unaccent, french_stem;
            """,
            reverse_sql="""
                DROP TEXT SEARCH CONFIGURATION french_unaccent;
            """,
        ),
    ]
