# Generated by Django 5.1.9 on 2025-06-17 06:44

from django.db import migrations
from django.db.models import Count, CharField
from uuid import uuid4


def dedup_organisation_names(apps, schema_editor):
    Organisation = apps.get_model("addressbook", "Organization")

    duplicate_names = [
        o.get("name")
        for o in (
            Organisation.objects.values("name")
            .annotate(name_count=Count("name"))
            .filter(name_count__gt=1)
            .order_by("name")
        )
    ]

    for name in duplicate_names:
        first_org = Organisation.objects.filter(name=name).order_by().first()
        for org in Organisation.objects.filter(name=name).exclude(id=first_org.id):
            org.name = f"{org.name} - {str(uuid4())[:8]}"
            org.save()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("addressbook", "0012_search_config_french_unaccent"),
    ]

    operations = [
        migrations.RunPython(
            dedup_organisation_names,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=CharField(max_length=90, unique=True, verbose_name="Nom"),
        ),
    ]
