# Generated by Django 5.1.14 on 2025-12-03 10:37

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("reminders", "0001_initial"),
        ("reminders", "0002_rename_sent_mail_sent_on"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.CharField(max_length=128)),
                ("subject", models.TextField(default="")),
                ("text", models.TextField(default="")),
                ("html", models.TextField(default="")),
                ("deadline", models.DateField()),
                ("sent_on", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "mail",
                "verbose_name_plural": "mails",
            },
            managers=[
                ("to_send", django.db.models.manager.Manager()),
            ],
        ),
    ]
