# Generated by Django 3.2.18 on 2023-10-23 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0093_project_last_members_activity_at"),
        ("reminders", "0006_auto_20220614_1453"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="kind",
            field=models.IntegerField(
                choices=[(0, "Nouvelle Recommandation"), (1, "Où en êtes-vous ?")],
                default=0,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reminder",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="projects.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reminder",
            name="state",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                verbose_name="Etat d'avancement de la fréquence de ce rappels",
            ),
        ),
    ]
