# Generated by Django 3.2.18 on 2023-10-23 15:48

from django.db import migrations
import django.db.models.manager
import recoco.apps.reminders.models


class Migration(migrations.Migration):
    dependencies = [
        ("reminders", "0008_reminders_on_site"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="reminder",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", recoco.apps.reminders.models.ReminderOnSiteManager()),
                (
                    "on_site_to_send",
                    recoco.apps.reminders.models.ToSendReminderOnSiteManager(),
                ),
                (
                    "on_site_sent",
                    recoco.apps.reminders.models.SentReminderOnSiteManager(),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="recipient",
        ),
    ]
