# Generated by Django 5.1.14 on 2025-12-03 10:37

import django.db.models.manager
import recoco.apps.reminders.models
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("reminders", "0009_auto_20231023_1748"),
        ("reminders", "0010_auto_20231023_1834"),
        ("reminders", "0011_alter_reminder_sent_on"),
    ]

    dependencies = [
        ("reminders", "0008_reminders_on_site"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="reminder",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", recoco.apps.reminders.models.ReminderOnSiteManager()),
                (
                    "on_site_to_send",
                    recoco.apps.reminders.models.ToSendReminderOnSiteManager(),
                ),
                (
                    "on_site_sent",
                    recoco.apps.reminders.models.SentReminderOnSiteManager(),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="object_id",
        ),
        migrations.AlterField(
            model_name="reminder",
            name="sent_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
