# Generated by Django 3.2.18 on 2023-10-23 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reminders", "0009_auto_20231023_1748"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reminder",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="object_id",
        ),
    ]
