# Generated by Django 3.2.23 on 2024-01-15 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reminders", "0009_auto_20231023_1748_squashed_0011_alter_reminder_sent_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="sent_to",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_reminders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
