# Generated by Django 4.2.19 on 2025-02-25 07:56

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("reminders", "0012_reminder_sent_to"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="reminder",
            index=models.Index(
                fields=["kind", "sent_on", "site", "project"],
                name="kind_sent_on_site_project",
            ),
        ),
    ]
