# Generated by Django 3.2.16 on 2022-11-04 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('next_challenge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.challengedefinition')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('challenge_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.challengedefinition')),
                ('next_challenge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
