# Generated by Django 3.2.16 on 2022-11-04 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_challengedefinition_next_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='acquired_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière mise à jour'),
        ),
    ]
