# Generated by Django 3.2.18 on 2023-06-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_auto_20230620_1214"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="acquired_on",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Date d'acquisition"
            ),
        ),
    ]
