# Generated by Django 3.2.16 on 2022-11-04 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20221104_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengedefinition',
            name='code',
            field=models.SlugField(default='2022-11-04 11:40:17.709206+00:00', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='acquired_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'acquisition"),
        ),
    ]
