# Generated by Django 3.2.16 on 2022-11-04 12:24

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20221104_1240'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='challenge',
            managers=[
                ('acquired_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='name',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='next_challenge',
        ),
        migrations.AddField(
            model_name='challengedefinition',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
