# Generated by Django 3.2.18 on 2023-06-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("training", "0006_auto_20230620_1540"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengedefinition",
            name="code",
            field=models.SlugField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name="challengedefinition",
            unique_together={("site", "code")},
        ),
    ]
