# Generated by Django 3.2.20 on 2023-08-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0007_auto_20230620_1815"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengedefinition",
            name="week_inactivity_repeat",
            field=models.IntegerField(default=0),
        ),
    ]
