# Generated by Django 3.2.20 on 2023-08-21 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0008_challengedefinition_week_inactivity_repeat"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="challenge",
            unique_together=set(),
        ),
    ]
