# Generated by Django 3.2.3 on 2021-07-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="text",
            field=models.CharField(default="Une question", max_length=255),
            preserve_default=False,
        ),
    ]
