# Generated by Django 3.2.3 on 2021-07-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0002_question_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="session",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="survey.session",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="answer",
            name="value",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="question_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="survey.questionset",
            ),
        ),
    ]
