# Generated by Django 3.2.3 on 2021-07-27 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0003_auto_20210727_1430"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="survey",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="survey.survey",
            ),
            preserve_default=False,
        ),
    ]
