# Generated by Django 3.2.3 on 2021-08-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0006_survey_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionset",
            name="icon",
            field=models.CharField(default="", max_length=80, verbose_name="Icône"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.CharField(max_length=255, verbose_name="Texte de la question"),
        ),
        migrations.AlterField(
            model_name="questionset",
            name="heading",
            field=models.CharField(max_length=255, verbose_name="En-tête"),
        ),
        migrations.AlterField(
            model_name="questionset",
            name="subheading",
            field=models.TextField(verbose_name="Sous-titre"),
        ),
    ]
