# Generated by Django 3.2.6 on 2021-08-04 09:35

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0009_choice_signals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="signals",
            field=tagging.fields.TagField(
                blank=True, max_length=255, verbose_name="Signaux"
            ),
        ),
    ]
