# Generated by Django 3.2.3 on 2021-08-09 13:17

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_alter_questionset_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='precondition',
            field=tagging.fields.TagField(blank=True, help_text='Affiche cette question si TOUS les signaux saisis sont émis', max_length=255, verbose_name='Pré-condition'),
        ),
    ]
