# Generated by Django 3.2.3 on 2021-08-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0013_answer_signals"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="priority",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Priorité d'affichage. Le plus fort, le plus important.",
                verbose_name="Priorité",
            ),
        ),
    ]
