# Generated by Django 3.2.6 on 2021-08-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0014_question_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="how",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="question",
            name="why",
            field=models.TextField(blank=True, default=""),
        ),
    ]
