# Generated by Django 3.2.6 on 2021-08-17 08:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0015_auto_20210817_1008"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="values",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="is_multiple",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
