# Generated by Django 3.2.6 on 2021-08-17 08:33

from django.db import migrations, models
import urbanvitaliz.apps.survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_auto_20210817_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='values',
            field=models.JSONField(blank=True, default=urbanvitaliz.apps.survey.models.empty_answer),
        ),
        migrations.AddField(
            model_name='question',
            name='is_multiple',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
