# Generated by Django 3.2.3 on 2021-08-17 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_auto_20210720_1232"),
        ("survey", "0017_session_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_session",
                to="projects.project",
            ),
        ),
    ]
