# Generated by Django 3.2.6 on 2021-08-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0018_alter_session_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="how",
            field=models.TextField(blank=True, default="", verbose_name="Comment ?"),
        ),
        migrations.AlterField(
            model_name="question",
            name="is_multiple",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Est un QCM ?"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="why",
            field=models.TextField(blank=True, default="", verbose_name="Pourquoi ?"),
        ),
    ]
