# Generated by Django 3.2.3 on 2021-09-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0019_auto_20210823_1513"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionset",
            name="deleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
