# Generated by Django 3.2.3 on 2021-09-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0021_question_comment_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionset",
            name="subheading",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Sous-titre"
            ),
        ),
    ]
