# Generated by Django 3.2.3 on 2021-09-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0022_alter_questionset_subheading"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="priority",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Priorité d'affichage. Le plus fort, le plus important.",
                verbose_name="Priorité",
            ),
        ),
    ]
