# Generated by Django 3.2.3 on 2021-09-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0025_choice_conclusion"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="question",
            name="upload_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Si rempli, il sera possible de téléverser un fichier",
                max_length=255,
                verbose_name="Titre du Téléversement",
            ),
        ),
    ]
