# Generated by Django 3.2.8 on 2021-10-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0027_alter_answer_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="text_short",
            field=models.CharField(
                default="", max_length=32, verbose_name="Texte court de la question"
            ),
        ),
        migrations.AddField(
            model_name="questionset",
            name="priority",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Priorité d'affichage. Le plus fort, le plus important.",
                verbose_name="Priorité",
            ),
        ),
    ]
