# Generated by Django 3.2.13 on 2022-05-23 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_merge_20220523_1203'),
        ('survey', '0032_alter_session_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_session', to='projects.project'),
        ),
    ]
