name: Deploy documentation to Pages

# Runs on pushes targeting the default branch
on:
  push:
    branches: [master]
  pull_request:
    branches: ['main', 'develop']


concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.1.5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install uv and python
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Dependencies
        run: |
          uv sync --no-dev
          uv sync --only-dev

      - uses: borales/actions-yarn@v5.0.0

      - id: install_jsdoc
        run: yarn add jsdoc

      - id: deployment
        uses: sphinx-notes/pages@v3
